import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {pbkdf2Sync,randomBytes} from 'node:crypto';
import fs from 'node:fs';
import {authResponse,authenticatedUser,SESSION_COOKIE} from './admin-auth.mjs';
import {picksResponse,rulesResponse,publicPicks} from './stock-rule-access.mjs';
import {exitsResponse} from './stock-exits-api.mjs';
const origin='https://shixu.example',password='unit-test-only-not-a-real-password';
const salt=randomBytes(16),verifier=JSON.stringify({iterations:100000,salt:salt.toString('hex'),hash:pbkdf2Sync(password,salt,100000,32,'sha256').toString('hex')});
function db(){const sqlite=new DatabaseSync(':memory:');for(const f of ['0001_sweet_anita_blake.sql','0002_robust_ogun.sql'])sqlite.exec(fs.readFileSync('drizzle/'+f,'utf8'));return {prepare:sql=>({bind:(...args)=>({first:async()=>sqlite.prepare(sql).get(...args),run:async()=>sqlite.prepare(sql).run(...args)})}),sqlite,close:()=>sqlite.close()};}
const env=DB=>({ADMIN_USERNAME:'admin',ADMIN_PASSWORD_VERIFIER:verifier,DB});
const req=(path,body,headers={})=>new Request(origin+'/api/'+path,{method:body?'POST':'GET',headers:{...(body?{Origin:origin,'Content-Type':'application/json'}:{}),...headers},body:body?JSON.stringify(body):undefined});
test('sell candidates in all four markets protect evidence and respect holdings filters',async()=>{
 const snapshots=JSON.parse(fs.readFileSync('.generated/stock-exits.json','utf8')),DB=db();
 try{const cookie=await signIn(DB);for(const market of ['CN','US','HK','FUND']){
  const guest=await exitsResponse(req('stock-exits?market='+market),env(DB),snapshots),body=await guest.json();
  assert.equal(guest.status,401);assert.equal(body.authenticated,false);assert.equal(body.rows,undefined);assert.equal(body.matched,undefined);assert.equal(body.rules,undefined);
  const code=snapshots[market].rows.find(r=>r.status==='triggered').code,member=await exitsResponse(req('stock-exits?market='+market+'&codes='+code,null,{Cookie:cookie}),env(DB),snapshots),full=await member.json();
  assert.equal(full.authenticated,true);assert.equal(full.rows.length,1);assert.equal(full.rows[0].code,code);assert.ok(full.rows[0].box.lower>0);assert.ok(full.rows[0].points.length>1);assert.ok(full.rules.every(r=>r.description));
  assert.equal(member.headers.get('Cache-Control'),'private, no-store');assert.equal(member.headers.get('Vary'),'Cookie');
  assert.equal((await (await exitsResponse(req('stock-exits?market='+market+'&codes=',null,{Cookie:cookie}),env(DB),snapshots)).json()).rows.length,0);
 }
 const {default:worker}=await import('./dist/server/index.js');
 assert.equal((await worker.fetch(req('stock-exits?market=fund'),env(DB))).status,401);
 assert.equal((await (await worker.fetch(req('stock-exits?market=fund',null,{Cookie:cookie}),env(DB))).json()).market,'FUND');
 assert.equal((await (await worker.fetch(req('stock-exits?market=us',null,{Cookie:cookie}),env(DB))).json()).authenticated,true);
 }finally{DB.close();}
});
async function signIn(DB){const r=await authResponse(req('auth/login',{username:'admin',password}),env(DB));assert.equal(r.status,200);return r.headers.get('Set-Cookie').split(';')[0];}

test('unconfigured preview is unavailable and fake local identity never grants access',async()=>{const s=await authResponse(req('auth/session'),{});assert.equal((await s.json()).configured,false);assert.equal((await authResponse(req('auth/login',{password}),{})).status,503);const DB=db();try{assert.equal(await authenticatedUser(req('auth/session',null,{'oai-authenticated-user-id':'spoof','X-Logged-In':'true',Cookie:SESSION_COOKIE+'='+'a'.repeat(64)}),env(DB)),null);}finally{DB.close();}});
test('password login stores only a session hash and uses a secure HttpOnly cookie',async()=>{const DB=db();try{const r=await authResponse(req('auth/login',{username:'admin',password}),env(DB));assert.equal(r.status,200);for(const flag of ['HttpOnly','Secure','SameSite=Lax','Path=/','Max-Age=28800'])assert.ok(r.headers.get('Set-Cookie').includes(flag));assert.deepEqual(await r.json(),{ok:true});const cookie=r.headers.get('Set-Cookie').split(';')[0],token=cookie.split('=')[1],row=DB.sqlite.prepare('SELECT token_hash FROM admin_sessions').get();assert.notEqual(row.token_hash,token);assert.deepEqual(await authenticatedUser(req('auth/session',null,{Cookie:cookie}),env(DB)),{id:'preview-admin',name:'admin'});}finally{DB.close();}});
test('wrong password, wrong username and cross-site POST cannot create sessions',async()=>{const DB=db();try{assert.equal((await authResponse(req('auth/login',{password:'incorrect'}),env(DB))).status,401);assert.equal((await authResponse(req('auth/login',{username:'other',password}),env(DB))).status,401);assert.equal((await authResponse(req('auth/login',{password},{Origin:'https://evil.example'}),env(DB))).status,403);assert.equal(DB.sqlite.prepare('SELECT COUNT(*) AS n FROM admin_sessions').get().n,0);}finally{DB.close();}});
test('database-backed rate limit blocks repeated password guesses',async()=>{const DB=db();try{for(let i=0;i<10;i++)assert.equal((await authResponse(req('auth/login',{password:'incorrect'}),env(DB))).status,401);assert.equal((await authResponse(req('auth/login',{password}),env(DB))).status,429);}finally{DB.close();}});
test('logout revokes the server session, replay fails and expired sessions fail',async()=>{const DB=db();try{const cookie=await signIn(DB),r=await authResponse(req('auth/logout',{}, {Cookie:cookie}),env(DB));assert.equal(r.status,200);assert.ok(r.headers.get('Set-Cookie').includes('Max-Age=0'));assert.equal(await authenticatedUser(req('auth/session',null,{Cookie:cookie}),env(DB)),null);const second=await signIn(DB);DB.sqlite.exec('UPDATE admin_sessions SET expires = 0');assert.equal(await authenticatedUser(req('auth/session',null,{Cookie:second}),env(DB)),null);}finally{DB.close();}});
test('rotating credentials invalidates existing sessions',async()=>{const DB=db();try{const cookie=await signIn(DB),changed={...env(DB),ADMIN_PASSWORD_VERIFIER:JSON.stringify({...JSON.parse(verifier),hash:'b'.repeat(64)})};assert.equal(await authenticatedUser(req('auth/session',null,{Cookie:cookie}),changed),null);}finally{DB.close();}});
test('all three markets keep candidates public but serve details only to an authenticated admin',async()=>{const snapshots=JSON.parse(fs.readFileSync('.generated/stock-picks.json','utf8')),DB=db();try{const cookie=await signIn(DB);for(const market of ['CN','US','HK']){const anonymous=await picksResponse(req('stock-picks?market='+market),env(DB),snapshots),body=await anonymous.json();assert.equal(body.authenticated,false);assert.deepEqual(body.rules,[{id:'R01'},{id:'R02'}]);assert.deepEqual(body.matches,publicPicks(snapshots[market]).matches);assert.ok(!JSON.stringify(body).includes('firstBreakDate'));assert.ok(!JSON.stringify(body).includes('rangeStart'));const member=await picksResponse(req('stock-picks?market='+market,null,{Cookie:cookie}),env(DB),snapshots),full=await member.json();assert.equal(full.authenticated,true);assert.ok(full.rules.every(r=>r.description));assert.ok(full.matches.every(r=>r.explanation));assert.equal(member.headers.get('Cache-Control'),'private, no-store');assert.equal(member.headers.get('Vary'),'Cookie');assert.equal(full.matches.length,body.matches.length);}const rules=await rulesResponse(req('stock-rules',null,{Cookie:SESSION_COOKIE+'=fake'}),env(DB));assert.equal((await rules.json()).authenticated,false);}finally{DB.close();}});
test('public stock assets contain neither rule details nor rule implementation',()=>{for(const f of ['index.html','header-demo.html','home-picks.js','stock-peers.js']){const content=fs.readFileSync('dist/client/'+f,'utf8');for(const secret of ['evaluateBreakout','amplitude<=.1','30自然日振幅≤10%','此前15自然日','15自然日横盘'])assert.ok(!content.includes(secret),f+': '+secret);}for(const f of ['stock-picks.json','us-stock-picks.json','hk-stock-picks.json']){const s=JSON.parse(fs.readFileSync('dist/client/'+f,'utf8'));assert.ok(s.matches.every(m=>!m.signal&&!m.chartBox&&!m.explanation&&!m.rule1&&!m.rule2));}});
test('built Worker dispatches authenticated and public paths correctly',async()=>{const {default:worker}=await import('./dist/server/index.js'),DB=db();try{const e=env(DB);const r=await worker.fetch(req('auth/login',{username:'admin',password}),e);assert.equal(r.status,200);const cookie=r.headers.get('Set-Cookie').split(';')[0];assert.equal((await (await worker.fetch(req('stock-picks?market=hk',null,{Cookie:cookie}),e)).json()).authenticated,true);assert.equal((await (await worker.fetch(req('stock-picks?market=hk'),e)).json()).authenticated,false);assert.equal((await (await worker.fetch(req('stock-rules'),e)).json()).rules[0].description,undefined);}finally{DB.close();}});
