import {companies,reviewedAt} from './company-data.mjs';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tags=['全部','主动权益','指数 / ETF','固收','量化','黄金','海外投资','养老配置'];let active='全部',products={};
$('companyFilters').innerHTML=tags.map(t=>`<button type="button" data-filter="${esc(t)}" aria-pressed="${t===active}">${esc(t)}</button>`).join('');
function card(c){return `<article class="company-card" id="${c.id}"><header class="company-card-head"><div class="company-kicker"><span>基金管理公司</span><span>公司画像</span></div><h2>${c.name}</h2><p class="company-headline">${c.headline}</p><div class="company-tags">${c.tags.map(t=>`<span>${t}</span>`).join('')}</div></header><div class="company-card-body"><h3>投资风格 · 资料归纳</h3><p class="company-style">${c.style}</p><h3>特色领域与业务积累</h3><div class="company-areas">${c.areas.map(([name,body])=>`<section><h4>${name}</h4><p>${body}</p></section>`).join('')}</div><details class="company-details"><summary>看依据、选基要点与示例产品</summary><section><span class="fact-label">公开事实</span><p>${c.fact}</p><div class="company-sources">${c.sources.map(([title,url])=>`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${title}</a>`).join('')}</div></section><section><span class="fact-label interpret">本站解读</span><p>${c.take}</p><ul>${c.checks.map(t=>`<li>${t}</li>`).join('')}</ul></section><section><h3>用具体产品验证差异</h3><p>示例并非优选排名，点击后可加入同板块对比。</p><div class="company-products">${c.products.map(code=>{const p=products[code];return p?`<a href="/compare.html?code=${code}"><span>${esc(p.name)}<small>${code} · ${esc(p.type)}</small></span><b>去对比</b></a>`:'';}).join('')||'<p>产品示例尚未载入，可先查看公司来源。</p>'}</div></section></details><footer class="company-card-footer"><span>资料核对 ${reviewedAt}</span><a href="/compare.html?q=${encodeURIComponent(c.short)}">搜索旗下基金</a></footer></div></article>`;}
function render(){const openIds=[...document.querySelectorAll('.company-details[open]')].map(d=>d.closest('article').id);const q=$('companyQuery').value.trim().toLowerCase();const rows=companies.filter(c=>(active==='全部'||c.tags.includes(active))&&[c.name,c.headline,c.style,...c.tags,...c.areas.flat()].join(' ').toLowerCase().includes(q));
 $('companyCount').textContent=`${rows.length} / ${companies.length} 家 · 特色布局，不作收益排名`;
 $('companyGrid').innerHTML=rows.map(card).join('')||'<div class="company-empty"><h2>暂未收录符合条件的公司画像</h2><p>本页首批整理8家，可更换关键词，或清除条件查看全部。</p><button id="clearCompanies">清除筛选</button></div>';
 for(const id of openIds){const details=document.getElementById(id)?.querySelector('details');if(details)details.open=true;}
 for(const b of $('companyFilters').querySelectorAll('button'))b.setAttribute('aria-pressed',String(b.dataset.filter===active));
}
function openLinkedCompany(){const id=location.hash.slice(1);if(!companies.some(c=>c.id===id))return;active='全部';$('companyQuery').value='';render();const card=document.getElementById(id);card.querySelector('details').open=true;card.scrollIntoView({block:'start'});}
$('companyQuery').addEventListener('input',render);$('companyFilters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(b){active=b.dataset.filter;render();}});$('companyGrid').addEventListener('click',e=>{if(e.target.closest('#clearCompanies')){active='全部';$('companyQuery').value='';render();$('companyQuery').focus();}});
render();openLinkedCompany();window.addEventListener('hashchange',openLinkedCompany);
try{const response=await fetch('/company-products.json');if(!response.ok)throw Error();products=await response.json();render();}catch{document.querySelectorAll('.company-products').forEach(el=>el.innerHTML='<p>产品示例暂未取得，请通过卡片底部搜索旗下基金。</p>');}
