import {INDICES,sourceURL,localStamp,chartPoints,quoteStatus} from './market-indices-core.mjs';
const grid=document.getElementById('indexCards'),note=document.getElementById('indexUpdate'),dialog=document.getElementById('indexDialog');
const orderedIndices=['cn','us','hk'].flatMap(market=>INDICES.filter(index=>index.market===market));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n),signed=n=>(n>0?'+':'')+n.toFixed(2);
let data={rows:[]},market=new URL(location.href).searchParams.get('market')||'cn',opened='',busy=false,failed=false;
function plot(points,large=false){
 if(points.length<2)return '<span class="index-no-chart">走势暂未取得</span>';
 const width=large?740:180,height=large?260:45,pad=large?45:3,top=large?22:4,bottom=large?35:4;
 const vals=points.map(p=>p[1]),lo=Math.min(...vals),hi=Math.max(...vals),span=hi-lo||hi*.001;
 const x=i=>pad+i/(points.length-1)*(width-2*pad),y=v=>top+(hi-v)/span*(height-top-bottom);
 const line=points.map((p,i)=>x(i).toFixed(2)+','+y(p[1]).toFixed(2)).join(' ');
 return `<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="${esc(points[0][0])}至${esc(points.at(-1)[0])}指数点位走势">${large?[lo,(lo+hi)/2,hi].map(v=>`<line x1="${pad}" x2="${width-pad}" y1="${y(v)}" y2="${y(v)}" stroke="currentColor" opacity=".1"/><text x="${pad}" y="${y(v)-6}" font-size="10" fill="currentColor" opacity=".6">${fmt(v)}</text>`).join(''):''}<polyline points="${line}" fill="none" stroke="currentColor" stroke-width="${large?2.4:1.8}" stroke-linecap="round" stroke-linejoin="round"/><circle cx="${x(points.length-1)}" cy="${y(points.at(-1)[1])}" r="${large?3:2}" fill="currentColor"/>${large?`<text x="${pad}" y="${height-6}" font-size="11" fill="currentColor">${points[0][0]}</text><text x="${width-pad}" y="${height-6}" text-anchor="end" font-size="11" fill="currentColor">${points.at(-1)[0]}</text>`:''}</svg>`;
}
function render(){
 grid.innerHTML=orderedIndices.map(i=>{const row=data.rows.find(r=>r.id===i.id)||{},q=row.quote,points=chartPoints(row);return `<button class="index-card ${q?(q.change>0?'index-up':q.change<0?'index-down':''):''} ${market===i.market?'index-selected':''}" data-index="${i.id}" aria-label="${i.name}，${q?fmt(q.price)+'点，涨跌'+signed(q.percent)+'%，查看走势':'行情暂未取得'}" aria-haspopup="dialog"><span class="index-name">${i.name}<small>${i.short}</small></span><strong class="index-price">${q?fmt(q.price):'—'}</strong><span class="index-change">${q?signed(q.percent)+'%':'待更新'}<small>${q?signed(q.change)+' 点':''}</small></span><div class="index-spark">${plot(points)}</div><span class="index-asof">${q?localStamp(q.time,i.zone).slice(5,16)+' · '+i.zoneLabel:'正在获取行情'}</span><span class="index-status">${quoteStatus(row,i)}</span></button>`;}).join('');
 if(opened)renderDialog();
}
function renderDialog(){const i=INDICES.find(i=>i.id===opened),r=data.rows.find(r=>r.id===opened)||{},q=r.quote,points=chartPoints(r);document.getElementById('indexDialogTitle').textContent=i.name;document.getElementById('indexDetail').innerHTML=`<div class="index-detail-numbers ${q?.change>0?'index-up':'index-down'}"><b>${q?fmt(q.price):'—'}</b><span>${q?signed(q.percent)+'% · '+signed(q.change)+' 点':'行情暂未取得'}</span></div><p class="index-detail-date">${q?localStamp(q.time,i.zone)+' '+i.zoneLabel+' · '+quoteStatus(r,i):'请稍后刷新重试'}</p><div class="index-large-chart">${plot(points,true)}</div><p>近30自然日日线。末点使用标注时间的最新点位，盘中会变化；曲线展示期间走势，上方涨跌幅相对于前一交易日收盘。</p>${r.historyFailed?'<p class="index-warning">历史走势更新失败，当前展示可用的历史片段。</p>':''}<a href="${sourceURL(i)}" target="_blank" rel="noopener">查看腾讯证券行情来源</a><small>可能存在行情延迟，各市场时间与交易时段不同。</small>`;}
grid.addEventListener('click',e=>{const b=e.target.closest('[data-index]');if(!b)return;opened=b.dataset.index;renderDialog();dialog.showModal();});
document.getElementById('indexDialogClose').onclick=()=>dialog.close();dialog.addEventListener('close',()=>opened='');dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
document.addEventListener('demo:market',e=>{market=e.detail.market;grid.querySelectorAll('[data-index]').forEach(el=>el.classList.toggle('index-selected',INDICES.find(i=>i.id===el.dataset.index).market===market));});
async function refresh(){if(busy||document.hidden)return;busy=true;document.getElementById('indexRefresh').disabled=true;try{const r=await fetch('/api/market-indices',{signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error();const next=await r.json();if(!Array.isArray(next.rows)||next.rows.length!==6)throw Error();data=next;failed=false;note.textContent=next.rows.some(r=>r.fallback||!r.quote)?'部分行情更新失败 · 旧数据已标注':'每分钟尝试更新 · 以各卡片行情时间为准';}catch{failed=true;data.rows=data.rows.map(r=>({...r,fallback:!!r.quote}));note.textContent='更新暂未成功 · 展示已标注时间的快照，可重试';}finally{busy=false;document.getElementById('indexRefresh').disabled=false;render();}}
document.getElementById('indexRefresh').onclick=refresh;
try{data=JSON.parse(document.getElementById('indexSnapshot').textContent);data.rows=data.rows.map(r=>({...r,fallback:!!r.quote}));}catch{}render();
refresh();setInterval(refresh,60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});
