const $=id=>document.getElementById(id),reduce=matchMedia('(prefers-reduced-motion: reduce)'),tabs=[...document.querySelectorAll('[data-market]')];
const markets={fund:['#d3ef9a','01 / FUND','把时间，变成你的观察尺度。','从筛选到对比，再用一次历史演练验证判断。',[['今日筛选','规则组合，发现值得观察的基金。'],['同板块对比','比较走势、持仓与费用。'],['历史演练','用虚拟资金练习自己的判断。']]],cn:['#b4d8ff','02 / A-SHARE','发现机会，也看懂同行。','用规则缩小范围，再从经营与成长中寻找差异。',[['近30天候选','观察横盘与确认突破的交集。'],['同板块对比','从规模、经营、成长与走势研究。'],['历史演练','回到过去，做出自己的选择。']]],us:['#e1d8ff','03 / US STOCKS','换个市场，打开新的视野。','先认识公司，再把它与同行放在一起看。',[['美股候选','从中文业务简介认识公司。'],['同行对比','比较经营数据与美元走势。']]],hk:['#ffe2c3','04 / HONG KONG','把视线，投向同一个行业。','拉长观察周期，理解公司之间的差异。',[['同行对比','比较规模、经营质量与成长。'],['长期走势','半年与一年，换一个时间尺度。']]]};
let active='fund',panelAnimation,heightAnimation,extraAnimation,dialogAnimation;
function animate(el,frames,options){if(reduce.matches)return null;return el.animate(frames,{easing:'cubic-bezier(.22,1,.36,1)',...options});}
function alignIndicator(){const b=tabs.find(t=>t.dataset.market===active);$('tabIndicator').style.width=b.offsetWidth+'px';$('tabIndicator').style.transform=`translateX(${b.offsetLeft-7}px)`;}
function switchMarket(key){const old=tabs.findIndex(t=>t.dataset.market===active),index=tabs.findIndex(t=>t.dataset.market===key),before=$('workspace').getBoundingClientRect().height;active=key;panelAnimation?.cancel();heightAnimation?.cancel();const [color,en,title,desc,actions]=markets[key];document.documentElement.style.setProperty('--accent',color);tabs.forEach(t=>{const on=t.dataset.market===key;t.setAttribute('aria-selected',String(on));t.tabIndex=on?0:-1;});$('workspace').setAttribute('aria-labelledby','tab-'+key);$('marketEnglish').textContent=en;$('marketTitle').textContent=title;$('marketNumber').textContent=en.slice(0,2);$('marketDesc').textContent=desc;$('actions').replaceChildren(...actions.map(([title,desc])=>{const b=document.createElement('button');b.className='action';b.innerHTML=`<b>${title}<span></span></b><small>${desc}</small>`;b.onclick=()=>openDialog(title);b.onpointermove=e=>{if(e.pointerType==='touch'||reduce.matches)return;const r=b.getBoundingClientRect();b.style.setProperty('--x',e.clientX-r.left+'px');b.style.setProperty('--y',e.clientY-r.top+'px');};return b;}));alignIndicator();const after=$('workspace').getBoundingClientRect().height;heightAnimation=animate($('workspace'),[{height:before+'px'},{height:after+'px'}],{duration:330});panelAnimation=animate($('workspaceContent'),[{opacity:0,transform:`translateX(${index>=old?14:-14}px)`},{opacity:1,transform:'translateX(0)'}],{duration:350});document.dispatchEvent(new CustomEvent('demo:market',{detail:{market:key}}));}
tabs.forEach((b,i)=>{b.onclick=()=>switchMarket(b.dataset.market);b.onkeydown=e=>{let n;if(e.key==='ArrowRight')n=(i+1)%4;else if(e.key==='ArrowLeft')n=(i+3)%4;else if(e.key==='Home')n=0;else if(e.key==='End')n=3;else return;e.preventDefault();tabs[n].focus();switchMarket(tabs[n].dataset.market);};});new ResizeObserver(alignIndicator).observe($('marketNav'));
new IntersectionObserver(([e])=>$('marketNav').classList.toggle('stuck',!e.isIntersecting),{rootMargin:'-12px 0px 0px 0px'}).observe($('sentinel'));
document.documentElement.classList.add('motion-ready');const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target);}}),{threshold:.12});document.querySelectorAll('.reveal').forEach((el,i)=>{el.style.setProperty('--delay',el.classList.contains('sample')?((i-1)%3)*65+'ms':'0ms');observer.observe(el);});
function entrance(){document.querySelectorAll('.intro-copy,.market-nav,.workspace').forEach((el,i)=>{el.getAnimations().forEach(a=>a.cancel());animate(el,[{opacity:0,transform:'translateY(16px)'},{opacity:1,transform:'translateY(0)'}],{duration:550,delay:i*65,fill:'backwards'});});} $('replay').onclick=entrance;
let expanded=false;$('expand').onclick=()=>{extraAnimation?.cancel();const el=$('extra');if(!expanded){expanded=true;el.hidden=false;extraAnimation=animate(el,[{height:0,opacity:0},{height:el.scrollHeight+'px',opacity:1}],{duration:400});}else{expanded=false;extraAnimation=animate(el,[{height:el.getBoundingClientRect().height+'px',opacity:1},{height:0,opacity:0}],{duration:260});if(extraAnimation)extraAnimation.finished.then(()=>{if(!expanded)el.hidden=true;}).catch(()=>{});else el.hidden=true;} $('expand').setAttribute('aria-expanded',String(expanded));$('expand').innerHTML=expanded?'收起内容 <span>−</span>':'展开更多 <span>＋</span>';};
const dialog=$('demoDialog');let closing=false;function openDialog(title){dialogAnimation?.cancel();closing=false;$('dialogTitle').textContent=title;if(!dialog.open)dialog.showModal();document.body.style.overflow='hidden';dialogAnimation=animate(dialog,[{opacity:0,transform:'translateY(24px) scale(.97)'},{opacity:1,transform:'translateY(0) scale(1)'}],{duration:350});}function closeDialog(){if(closing||!dialog.open)return;closing=true;dialogAnimation?.cancel();dialogAnimation=animate(dialog,[{opacity:1,transform:'translateY(0)'},{opacity:0,transform:'translateY(12px)'}],{duration:180});const done=()=>{dialog.close();closing=false;document.body.style.overflow='';};if(dialogAnimation)dialogAnimation.finished.then(done).catch(()=>{});else done();} $('closeDialog').onclick=closeDialog;$('confirmDialog').onclick=closeDialog;dialog.addEventListener('cancel',e=>{e.preventDefault();closeDialog();});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>openDialog(b.dataset.detail));$('backTop').onclick=()=>$('marketNav').scrollIntoView({behavior:reduce.matches?'instant':'smooth',block:'start'});reduce.addEventListener('change',()=>{document.getAnimations().forEach(a=>a.finish());});switchMarket('fund');entrance();
