import {MARKETS,emptyBook,validateBook,analyzePortfolio,holdingOverlap} from './portfolio-core.mjs';
import {tagsFor,compareSeries} from './compare-core.mjs';
import {priceMetrics} from './stock-peers-core.mjs';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='shixu-holdings-v1',money=n=>new Intl.NumberFormat('zh-CN',{maximumFractionDigits:2,minimumFractionDigits:2}).format(n),pct=n=>Number.isFinite(n)?(n>=0?'+':'')+(n*100).toFixed(2)+'%':'—';
let market=new URL(location.href).searchParams.get('market')||'fund';if(!Object.hasOwn(MARKETS,market))market='fund';
const books=Object.fromEntries(Object.keys(MARKETS).map(m=>[m,emptyBook()])),catalogs={},evidence={},catalogPromises={},groupPromises={};
let catalog=[],editCode='',reportVisible=false,generation=0,busy=false;
try{const saved=JSON.parse(localStorage.getItem(KEY)||'{}');for(const m of Object.keys(books))if(saved[m]&&validateBook(saved[m],m).length===0)books[m]=saved[m];}catch{}
const book=()=>books[market],num=id=>$(id).value.trim()===''?null:Number($(id).value),note=(id,text)=>{$(id).textContent=text;$(id).hidden=!text;};
function save(){try{const stored=JSON.parse(localStorage.getItem(KEY)||'{}');for(const m of Object.keys(books))if(!validateBook(books[m],m).length)stored[m]=books[m];localStorage.setItem(KEY,JSON.stringify(stored));$('saveStatus').textContent=validateBook(book(),market).length?'输入待修正 · 本次修改尚未保存':'已保存在当前浏览器';}catch{$('saveStatus').textContent='浏览器未允许保存 · 关闭本页后会丢失';}}
function settings(){const b=book();b.date=$('bookDate').value;b.cash=num('cash');for(const id of ['reserve','singleLimit','sectorLimit'])b[id]=num(id);b.horizon=$('horizon').value;save();if(reportVisible)renderReport();}
for(const id of ['bookDate','cash','horizon','reserve','singleLimit','sectorLimit'])$(id).addEventListener('change',settings);
async function getJSON(url,timeout=18000){const r=await fetch(url,{signal:AbortSignal.timeout(timeout)});if(!r.ok)throw Error('资料暂未取得');return r.json();}
function loadCatalog(m){if(catalogPromises[m])return catalogPromises[m];catalogPromises[m]=(async()=>{if(m==='fund'){const d=await getJSON('/portfolio-funds.json');return d.rows.map(r=>({...r,sector:tagsFor(r)[0]||'',classification:'基金名称线索，添加前请核对',known:true}));}const root={cn:'stock-peer-data',us:'us-peer-data',hk:'hk-peer-data'}[m],d=await getJSON('/'+root+'/index.json'),map=new Map(d.industries.map(i=>[i.id,i]));return d.stocks.map(r=>({...r,sector:map.get(r.industry)?.name||'',classification:'公开行业分类 · '+d.asof,known:true,root}));})().catch(e=>{delete catalogPromises[m];throw e;});return catalogPromises[m];}
async function switchMarket(m){generation++;busy=false;market=m;reportVisible=false;resetAdd();note('accountError','');$('searchResults').hidden=true;const b=book(),meta=MARKETS[m];$('bookDate').value=b.date;for(const id of ['cash','reserve','singleLimit','sectorLimit','horizon'])$(id).value=b[id]??'';$('bookNote').textContent=meta.name+'独立账户 · 金额统一使用'+meta.unit+'（'+meta.currency+'） · 不与其他市场合并';document.querySelectorAll('[data-unit]').forEach(n=>n.textContent='· '+meta.unit);document.querySelectorAll('[data-market]').forEach(n=>{n.setAttribute('aria-selected',String(n.dataset.market===m));n.tabIndex=n.dataset.market===m?0:-1;});$('assetCode').placeholder=m==='us'?'例如 NVDA':m==='hk'?'例如 00700':'六位代码';$('compareLink').href=m==='fund'?'/compare':'/stock-peers?market='+m;const url=new URL(location.href);url.searchParams.set('market',m);history.replaceState(null,'',url);document.dispatchEvent(new CustomEvent('demo:market',{detail:{market:m}}));$('diagnosis').innerHTML='<div class="pf-empty"><span>03 / YOUR NEXT MOVE</span><h2>让下一步有据可依。</h2><p>录入持仓，设置自己的边界，再生成分析。</p></div>';$('evidenceStatus').textContent='';$('refreshEvidence').disabled=!b.rows.length;renderPositions();catalog=[];$('catalogStatus').textContent='正在读取'+meta.name+'名单…';try{const rows=await loadCatalog(m);catalogs[m]=rows;if(market!==m)return;catalog=rows;$('catalogStatus').textContent='可搜索 '+rows.length.toLocaleString()+' 只已收录产品；名单外可手动填写。';}catch{if(market===m)$('catalogStatus').textContent='名单暂未载入，可以手动填写代码和名称。';}}
document.querySelectorAll('[data-market]').forEach(b=>b.onclick=()=>switchMarket(b.dataset.market));
document.querySelector('.pf-markets').onkeydown=e=>{const keys=['fund','cn','us','hk'];let i=keys.indexOf(market);if(e.key==='ArrowRight')i=(i+1)%4;else if(e.key==='ArrowLeft')i=(i+3)%4;else return;e.preventDefault();switchMarket(keys[i]);document.querySelector('[data-market="'+keys[i]+'"]').focus();};
function choose(r){$('assetCode').value=r.code;$('assetName').value=r.name;$('assetSector').value=r.sector||'';$('sectorHint').textContent=r.classification||'请核对主分类';$('securityQuery').value=r.name+' '+r.code;$('searchResults').hidden=true;$('assetValue').focus();}
$('securityQuery').oninput=()=>{const q=$('securityQuery').value.trim().toLowerCase();if(!q){$('searchResults').hidden=true;return;}const hits=catalog.filter(r=>r.code.toLowerCase().includes(q)||r.name.toLowerCase().includes(q)||r.englishName?.toLowerCase().includes(q)).slice(0,12);$('searchResults').innerHTML=hits.map(r=>`<button type="button" data-found="${esc(r.code)}"><b>${esc(r.name)}</b><span>${esc(r.code)} · ${esc(r.sector||'分类待确认')}</span></button>`).join('')||'<p>没有找到，可在下方手动填写。</p>';$('searchResults').hidden=false;};
$('searchResults').onclick=e=>{const c=e.target.closest('[data-found]')?.dataset.found;if(c)choose(catalog.find(r=>r.code===c));};$('securityQuery').onkeydown=e=>{if(e.key==='Escape')$('searchResults').hidden=true;};
$('assetCode').onchange=()=>{let c=$('assetCode').value.trim().toUpperCase();if(market==='hk'&&/^\d{1,5}$/.test(c))c=c.padStart(5,'0');const r=catalog.find(r=>r.code===c);if(r)choose(r);};
function resetAdd(){editCode='';$('addForm').reset();$('cancelEdit').hidden=true;$('addButton').textContent='确认并加入持仓 ＋';note('formError','');}
$('cancelEdit').onclick=resetAdd;
$('addForm').onsubmit=e=>{e.preventDefault();settings();let code=$('assetCode').value.trim().toUpperCase();if(market==='hk'&&/^\d{1,5}$/.test(code))code=code.padStart(5,'0');const known=catalog.find(r=>r.code===code);const r={code,name:known?.name||$('assetName').value.trim(),sector:$('assetSector').value.trim(),value:num('assetValue'),cost:num('assetCost'),target:num('assetTarget'),known:!!known,industry:known?.industry||'',type:known?.type||''};const candidate={...book(),rows:[...book().rows.filter(r=>r.code!==editCode),r]},errors=validateBook(candidate,market);if(errors.length)return note('formError',errors.join('；'));books[market]=candidate;generation++;busy=false;save();resetAdd();renderPositions();$('refreshEvidence').disabled=false;if(reportVisible)renderReport();};
function renderPositions(){const b=book();$('positionList').innerHTML=b.rows.length?`<div class="pf-table-scroll"><table><thead><tr><th>持仓 / 主板块</th><th>市值</th><th>剩余成本</th><th>目标仓位</th><th>操作</th></tr></thead><tbody>${b.rows.map(r=>`<tr><td><b>${esc(r.name)}</b><small>${esc(r.code)} · ${esc(r.sector||'板块待填写')}${r.known?'':' · 手动录入'}</small></td><td>${money(r.value)}</td><td>${r.cost===null?'未填写':money(r.cost)}</td><td>${r.target===null?'未设置':r.target+'%'}</td><td><button data-edit="${esc(r.code)}">编辑</button><button data-delete="${esc(r.code)}" aria-label="移除${esc(r.name)}">移除</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="pf-entry-empty">还没有持仓。先加一只你已经持有的产品。</div>';}
$('positionList').onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.delete){books[market].rows=book().rows.filter(r=>r.code!==b.dataset.delete);generation++;busy=false;$('refreshEvidence').disabled=!book().rows.length;save();renderPositions();if(reportVisible)renderReport();return;}if(b.dataset.edit){const r=book().rows.find(r=>r.code===b.dataset.edit);editCode=r.code;for(const [id,key]of [['assetCode','code'],['assetName','name'],['assetSector','sector'],['assetValue','value'],['assetCost','cost'],['assetTarget','target']])$(id).value=r[key]??'';$('addButton').textContent='保存这只持仓';$('cancelEdit').hidden=false;$('addForm').scrollIntoView({behavior:'smooth',block:'center'});$('assetValue').focus({preventScroll:true});}};
function chart(points){if(!points?.length)return '';const v=points.map(p=>p[1]),lo=Math.min(...v),hi=Math.max(...v),span=Math.max(.001,hi-lo);return `<svg class="pf-spark" viewBox="0 0 240 54" role="img" aria-label="已披露区间相对走势"><polyline fill="none" stroke="currentColor" stroke-width="2.5" points="${v.map((n,i)=>(4+i/Math.max(1,v.length-1)*232).toFixed(1)+','+(48-(n-lo)/span*40).toFixed(1)).join(' ')}"/></svg>`;}
function factMarkup(r){const f=evidence[market]?.[r.code];if(!f)return '<p class="pf-muted">公开资料尚未核验。</p>';return `<div class="pf-facts">${f.error?`<p class="pf-error">${esc(f.error)}</p>`:''}${f.price?.known?`<div><b>近30自然日 ${pct(f.price.change)}</b><span>区间最大回撤 ${(f.price.drawdown*100).toFixed(2)}%</span>${chart(f.price.points)}<small>${esc(f.price.start)} — ${esc(f.price.end)} · 公开走势，与你的持仓收益不同</small></div>`:'<p class="pf-muted">'+esc(f.price?.reason||'走势数据未取得')+'</p>'}${f.screen?`<p>${esc(f.asof)} 快照 · 现有筛选规则：横盘 ${f.screen.range===true?'符合':f.screen.range===false?'不符合':'待核实'} · 突破 ${f.screen.breakout===true?'已确认':f.screen.breakout===false?'未确认':'待核实'}。未确认突破不等于卖出信号。</p>`:''}${f.holdings?.items?.length?`<p>披露前三大：${f.holdings.items.map(h=>esc(h.name)+(Number.isFinite(h.weight)?' '+h.weight.toFixed(2)+'%':'')).join(' / ')}</p><small>报告期 ${esc(f.holdings.date)} · 占基金净值 · 非完整或实时持仓${/联接/.test(r.name)?' · 未穿透目标ETF':''}</small>`:market==='fund'?'<p class="pf-muted">前三大直接股票持仓尚未取得，请核对披露。</p>':''}<a href="${market==='fund'?'/compare?code='+r.code:'/stock-peers?'+new URLSearchParams({market,code:r.code})}" target="_blank" rel="noopener">查看完整对比与数据来源</a></div>`;}
function renderReport(){const b=book(),a=analyzePortfolio(b,market);if(a.errors.length){note('accountError',a.errors.join('；'));$('diagnosis').innerHTML='<div class="pf-empty">输入已变化，请先修正上方错误后重新分析。</div>';return;}note('accountError','');const unit=MARKETS[market].unit,coverage=a.costCoverage+'/'+b.rows.length+'只已填成本',e=evidence[market]||{},overlap=market==='fund'?holdingOverlap(b.rows,e):[];
 $('diagnosis').innerHTML=`<div class="pf-report-heading"><span class="pf-eyebrow">03 / YOUR NEXT MOVE</span><h2>你的${MARKETS[market].name}持仓诊断</h2><p>${esc(b.date)} 录入市值 · ${unit}口径 · 占比以本账户总资产为分母</p></div><div class="pf-metrics"><article><span>本账户总资产</span><strong>${money(a.total)}</strong><small>持仓 ${money(a.held)} ＋ 现金 ${money(b.cash)}</small></article><article><span>${a.costCoverage===b.rows.length?'持仓浮动盈亏':'已填成本部分浮盈亏'}</span><strong>${a.costCoverage?pct(a.profitRate):'—'}</strong><small>${a.costCoverage?money(a.profit)+' '+unit+' · ':''}${coverage} · 非账户总收益</small></article><article><span>实际产品数量</span><strong>${a.productCount} <i>组</i></strong><small>${b.rows.length}条持仓${market==='fund'?' · 同名份额合并检查集中度':''}</small></article></div>
 <div class="pf-analysis-grid"><section class="pf-panel"><h3>钱分布在哪里</h3>${[...a.distribution,...(a.unknownValue?[{name:'未分类',value:a.unknownValue}]:[]),{name:'可用现金',value:b.cash}].map(d=>`<div class="pf-allocation"><div><span>${esc(d.name)}</span><b>${(a.total?d.value/a.total*100:0).toFixed(1)}%</b></div><i><em style="width:${a.total?d.value/a.total*100:0}%"></em></i><small>${money(d.value)} ${unit}</small></div>`).join('')}</section><section class="pf-panel"><h3>优先处理什么</h3>${a.issues.length?a.issues.map((i,n)=>`<article class="pf-issue"><span>0${n+1}</span><div><b>${esc(i.title)}</b><p>${esc(i.text)}</p>${i.amount!==null?`<small>${i.type==='unknown'?'未分类市值':'对应差额'} ${money(i.amount)} ${unit}</small>`:''}</div></article>`).join(''):'<div class="pf-calm"><b>已填写的边界内，暂无超限</b><p>这只说明录入的仓位与现金符合你的设置，不代表产品低风险或值得加仓。</p></div>'}</section></div>
 <section class="pf-plan ${a.allowed?'':'pf-plan-blocked'}"><div><span class="pf-eyebrow">A CONCRETE PLAN / 金额草案</span><h2>${a.allowed?a.sell||a.buy?'下一步，可以这样调整。':'当前没有金额调整要求。':'先补齐这些，金额才有依据。'}</h2></div>${a.blocks.length?`<ul>${a.blocks.map(s=>`<li>${esc(s)}</li>`).join('')}</ul><a href="#preferences">返回完善设置 ↑</a>`:`<div class="pf-plan-numbers"><div><span>计划减少</span><b>${money(a.sell)}</b></div><div><span>目标增加</span><b>${money(a.buy)}</b></div><div><span>调整后现金（未扣费）</span><b>${money(a.cashAfter)}</b></div></div><p>${a.fullTargets?'按你为每只持仓设定的目标计算；需要卖出提供的资金，必须实际到账后才能用于新增。':'依次调整单一产品、板块、现金要求，金额不重复累计；同组内按市值比例分摊。'} 未计费用与税费，不按股数下单${market==='fund'?'；赎回前核对持有天数、赎回费和到账时间':'；交易前核对可卖数量、最小交易单位和费用'}。</p>`}</section>
 <div class="pf-position-advice">${a.plan.map(r=>{const f=e[r.code],fall=f?.price?.known&&f.price.change<0;return `<article class="pf-panel"><header><div><span>${esc(r.code)} · 当前仓位 ${(r.weight*100).toFixed(1)}%</span><h3>${esc(r.name)}</h3></div><b class="pf-action-tag">${a.allowed?r.action==='观察'?'观察 / 复核':r.action+' '+money(Math.abs(r.delta)):'待完善'}</b></header><p>${a.allowed?r.reasons.length?esc(r.reasons.join('；'))+'。调整后目标市值 '+money(r.targetValue)+' '+unit+'。':'当前填写的仓位规则未要求调整；保留原判断并继续复核。':'补齐上方条件后再看具体调整金额。'}</p><div class="pf-own-return">这只持仓浮盈亏 <b>${r.return===null?'未填成本':pct(r.return)+' / '+money(r.profit)+' '+unit}</b></div>${factMarkup(r)}<div class="pf-review-prompt"><b>复核条件</b><p>${fall?'近30日公开走势为负：检查最初持有理由是否变化，不能仅因亏损自动补仓或止损。':f?.screen?.breakout===true?'已匹配突破筛选：核对信号日期与原区间，再结合持有理由和仓位边界决定。':'市值、现金需求或投资判断变化时，更新输入并重新计算。'}${!f||f.error?' 公开资料缺失，先核验资料。':''}</p></div></article>`;}).join('')}</div>
 ${overlap.length?`<section class="pf-panel"><h3>基金披露片段里，有共同持股</h3>${overlap.map(p=>`<p><b>${esc(p.a)} × ${esc(p.b)}</b><br>${p.names.map(esc).join('、')}<small class="pf-muted">报告期 ${esc(p.dateA)} / ${esc(p.dateB)}${p.sameDate?'':' · 日期不同，只作线索'}</small></p>`).join('')}<p class="pf-muted">只比较已取得的前三大直接持股，不计算完整重合率；先核对完整报告，再决定是否合并相似持仓。</p></section>`:''}
 <section class="pf-stress"><div><h3>如果所有持仓同时下跌10%？</h3><p>简单情景演算：现金不变、持仓等幅下跌；不是概率预测，也不是最大损失。</p></div><strong>−${money(a.stressLoss)}<small>约占账户 ${(a.stressRate*100).toFixed(2)}%</small></strong></section>`;
}
async function verify(){if(busy||!book().rows.length)return;const m=market,token=++generation,rows=book().rows.map(r=>({...r}));busy=true;evidence[m]??={};$('refreshEvidence').disabled=true;let completed=0;const queue=[...rows];let fundData;if(m==='fund'){try{fundData=await getJSON('/compare-data.json',25000);}catch{}}
 async function worker(){while(queue.length){if(token!==generation)return;const r=queue.shift(),f={};try{if(m==='fund'){const source=fundData?.rows.find(x=>x.code===r.code);if(source){const c=compareSeries([source],fundData.context,30),v=c.metrics[0];f.price=v&&!v.error?{known:true,change:v.change,drawdown:v.drawdown,start:c.start,end:c.end,points:v.series}:{known:false,reason:v?.error||'走势不足'};}else f.price={known:false,reason:'名单未收录或净值快照未取得'};try{const h=await getJSON('/api/compare/holdings?code='+r.code,18000);if(h.code!==r.code||!Array.isArray(h.items))throw Error();f.holdings=h;}catch{f.error='持仓披露核验失败，可重试或查看公开来源。';}}else{const cat=(catalogs[m]||await loadCatalog(m)).find(s=>s.code===r.code);if(!cat)throw Error('当前股票名单未收录此代码');const path='/'+cat.root+'/'+encodeURIComponent(cat.industry)+'.json';groupPromises[path]??=getJSON(path).catch(err=>{delete groupPromises[path];throw err;});const group=await groupPromises[path],stock=group.stocks.find(s=>s.code===r.code);if(!stock)throw Error('行业快照未收录此代码');f.price=priceMetrics(stock,group.calendar,group.asof,30);f.screen=stock.screen;f.asof=group.asof;}}catch(err){f.error=err.message||'资料暂未取得';}if(token!==generation)return;evidence[m][r.code]=f;completed++;$('evidenceStatus').textContent='公开资料已核验 '+completed+'/'+rows.length+' · '+MARKETS[m].name;if(reportVisible)renderReport();}}
 await Promise.all([worker(),worker(),worker()]);if(token===generation){busy=false;$('refreshEvidence').disabled=false;$('evidenceStatus').textContent+=rows.some(r=>evidence[m][r.code]?.error)?' · 部分资料待核实，可重试':' · 数据日期见各持仓';}
}
$('analyze').onclick=()=>{settings();const errors=validateBook(book(),market);if(errors.length)return note('accountError',errors.join('；'));reportVisible=true;renderReport();$('diagnosis').scrollIntoView({behavior:'smooth',block:'start'});verify();};
$('refreshEvidence').onclick=()=>{settings();if(validateBook(book(),market).length)return;reportVisible=true;renderReport();verify();};
switchMarket(market);
