import test from 'node:test';
import assert from 'node:assert/strict';
import {stockExit,buildStockExits,buildFundExits} from './stock-exits-core.mjs';
import {exitView} from './stock-exits-api.mjs';
const date=i=>new Date(Date.UTC(2026,0,1+i)).toISOString().slice(0,10);
function sample(tail){const values=[...Array(30).fill(100),...tail],points=values.map((v,i)=>[date(i),v]);return {stock:{code:'123456',name:'Test',points,source:'https://example.com'},context:{asof:points.at(-1)[0],historyStart:date(0),calendar:points.map(p=>p[0])}};}
const check=tail=>{const {stock,context}=sample(tail);return stockExit(stock,context);};
test('two consecutive closes below original lower edge and unchanged R01 are required',()=>{const r=check([99,98]);assert.equal(r.status,'triggered');assert.deepEqual(r.signals.map(s=>s.id),['R01','R02']);assert.equal(r.box.lower,100);assert.equal(r.box.firstBreakDate,date(30));assert.equal(r.box.confirmDate,date(31));assert.equal(r.box.rangeEnd,date(29));});
test('one lower close and failed confirmation do not match',()=>{assert.equal(check([99]).status,'clear');assert.equal(check([99,100]).status,'clear');});
test('returning to exactly the original lower edge cancels the confirmed signal',()=>{assert.equal(check([99,98,100]).status,'clear');assert.equal(check([99,98,101]).status,'clear');});
test('R01 stays mandatory even when a downside break is confirmed',()=>{const r=check([96,94]);assert.equal(r.rule2,true);assert.equal(r.rule1,false);assert.equal(r.status,'clear');assert.equal(check([96,95]).status,'triggered');});
test('box excludes first break, remains fixed and cannot see future closes',()=>{const r=check([99,98,97]);assert.equal(r.box.lower,100);assert.equal(r.box.upper,100);const {stock,context}=sample([99,98,97]);assert.deepEqual(stockExit({...stock,points:[...stock.points,[date(40),200]]},context),r);});
test('missing or invalid observations become unknown rather than a selling recommendation',()=>{for(const mutate of [p=>p.filter((_,i)=>i!==20),p=>p.slice(0,-1),p=>p.map((v,i)=>i===20?[v[0],0]:v)]){const {stock,context}=sample([99,98]);assert.equal(stockExit({...stock,points:mutate(stock.points)},context).status,'unknown');}});
test('anonymous view exposes no sell candidates; member details match',()=>{const {stock,context}=sample([99,98]),snapshot=buildStockExits({...context,stocks:[stock],market:'CN'}),pub=exitView(snapshot,false),member=exitView(snapshot,true);assert.equal(pub.authenticated,false);assert.equal(pub.rows,undefined);assert.equal(pub.rules,undefined);assert.equal(member.rows[0].box.lower,100);assert.ok(member.rules.every(r=>r.description));assert.equal(exitView(snapshot,true,new Set()).rows.length,0);});
test('funds use the same two rules on reinvested NAV, exclude unresolved corporate actions',()=>{const {stock,context}=sample([99,98]);const row={code:'000001',name:'基金',history:stock.points.map((p,i)=>[i,p[1]])};const daily={context:{asof:context.asof,history_start:context.historyStart,dates:context.calendar},rows:[row]};assert.equal(buildFundExits(daily).rows[0].status,'triggered');row.history[30]=[30,99,1];row.history[31]=[31,98,1];assert.equal(buildFundExits(daily).rows[0].status,'clear');row.history[31][3]=1;assert.equal(buildFundExits(daily).rows[0].status,'unknown');});
