const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>Number(n).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
const pct=n=>(n>=0?'+':'')+(n*100).toFixed(2)+'%';
const signed=n=>(n>=0?'+':'−')+'¥'+money(Math.abs(n));
const tone=n=>n>0?'positive':n<0?'negative':'neutral';
export const chapterNames=['你的战绩','你的决策画像','收益的幕后主角','如果走另一条路','这一局的关键帧','成就与下一次'];
function heading(n,title,subtitle){return `<div class="chapter-heading"><span class="chapter-number">${String(n).padStart(2,'0')}</span><div><h2>${title}</h2><p>${subtitle}</p></div></div>`}
export function reportChart(v,index){
 const {run:r}=v,points=r.curve,chosen=points[Math.min(index,points.length-1)],last=points.at(-1),values=points.flatMap(p=>[p.total/r.initial-1,p.benchmark/r.initial-1]);
 let lo=Math.min(0,...values),hi=Math.max(0,...values);const padding=Math.max((hi-lo)*.12,.005);lo-=padding;hi+=padding;
 const x=i=>6+i*988/Math.max(1,points.length-1),y=n=>214-(n-lo)/(hi-lo)*208,line=key=>points.map((p,i)=>`${x(i)},${y(p[key]/r.initial-1)}`).join(' '),at=Math.min(index,points.length-1),ret=chosen.total/r.initial-1,bench=chosen.benchmark/r.initial-1;
 const svg=`<svg viewBox="0 0 1000 220" preserveAspectRatio="none" role="img" aria-label="账户和沪深300价格收益曲线，从${esc(points[0].date)}到${esc(last.date)}"><path d="M0 6H1000 M0 110H1000 M0 214H1000" stroke="#d9e6df" stroke-dasharray="4 5"/><path d="M0 ${y(0)}H1000" stroke="#a9bfb5" stroke-dasharray="3 4"/><polyline points="${line('benchmark')}" fill="none" stroke="#8296b0" stroke-width="2" stroke-dasharray="6 5"/><polyline points="${line('total')}" fill="none" stroke="#117661" stroke-width="3" stroke-linejoin="round"/><path d="M${x(at)} 0V220" stroke="#fa7845" stroke-width="1.5" stroke-dasharray="3 3"/></svg>`;
 return `<div class="review-chart-top"><div><span class="chart-key own"></span>你的账户 <b>${pct(last.total/r.initial-1)}</b></div><div><span class="chart-key benchmark"></span>沪深300价格 <b>${pct(last.benchmark/r.initial-1)}</b></div></div><div class="return-chart"><div class="return-axis"><span>${pct(hi)}</span><span>${pct((hi+lo)/2)}</span><span>${pct(lo)}</span></div><div class="return-plot">${svg}</div></div><div class="return-dates"><span>${points[0].date}</span><span>${last.date}</span></div><label class="chart-scrubber">拖动回看每一天<input id="reportDay" type="range" min="0" max="${points.length-1}" step="1" value="${at}" aria-label="回看演练日期" ${points.length<2?'disabled':''}></label><div class="day-readout" aria-live="polite"><span>${chosen.date}<small>09:00可见的账户</small></span><span>收益率<b class="${tone(ret)}">${pct(ret)}</b></span><span>盈亏金额<b>${signed(chosen.total-r.initial)}</b></span><span>同期基准<b>${pct(bench)}</b></span></div>`;
}
export function reportMarkup(v,revealed=1){
 const {run:r,portfolio:p,report:a}=v,passed=p.return+1e-10>=r.target,top=a.contributors[0],bottom=a.contributors.at(-1),largest=Math.max(1,...a.contributors.map(c=>Math.abs(c.profit))),earned=a.badges.filter(b=>b.earned).length;
 const status=r.completed?(passed?'本局目标达成':'本局旅程完成'):'旅程进行中 · 阶段报告';
 const hero=`<header class="persona-card"><div class="persona-copy"><div class="eyebrow">YOUR FIELD NOTES / 第 ${r.elapsed} 天的你</div><span class="report-status">${status}</span><h2>${esc(a.role.name)}</h2><p class="persona-line">${esc(a.role.line)}</p><div class="persona-tags"><span>${esc(r.openingRegime)}开局</span><span>${a.filledCount}笔成交</span><span>${a.noteDays}天主动复盘</span></div><p class="persona-sample">${esc(a.sample)}</p></div><div class="persona-emblem" aria-label="本局风格代号 ${a.code}"><span class="emblem-symbol" aria-hidden="true">${a.role.icon}</span><b>${a.code}</b><small>本局行为画像</small></div><div class="hero-result"><div><span>${r.completed?'最终收益率':'当前收益率'}</span><strong>${pct(p.return)}</strong></div><div><span>账户盈亏 · 已计实际发生费用</span><b>${signed(a.profit)}</b><small>¥${money(r.initial)} → ¥${money(p.total)}</small></div><div><span>最大回撤</span><b>${(p.drawdown*100).toFixed(2)}%</b><small>目标 ${pct(r.target)} · 已推进 ${r.elapsed}/${r.duration||30} 天</small></div></div></header>`;
 const c1=`${heading(1,'先看结果，再回到当时。','收益率、金额与基准放在同一条时间线上。')}<p class="report-lead">${esc(a.closing)}</p><div id="reportChart">${reportChart(v,r.curve.length-1)}</div><div class="report-facts"><div><span>相对沪深300</span><b>${(p.excess>=0?'+':'')+(p.excess*100).toFixed(2)} 个百分点</b></div><div><span>累计费用</span><b>¥${money(p.fees)}</b></div><div><span>收益目标</span><b>${pct(r.target)}</b></div></div><p class="report-footnote">账户收益 =（总资产 − 初始本金）÷ 初始本金。包含现金、基金市值、冻结申购款及待到账款；已扣实际发生的教学费用，未强制清仓或预扣未来赎回费。沪深300为不含股息再投资的价格基准，与基金口径存在差异。图中日期为次日09:00的可见账户时点。</p>`;
 const c2=`${heading(2,'你的风格，藏在这些选择里。','四个观察维度，不给人贴永久标签。')}<div class="trait-grid">${a.dimensions.map((d,i)=>`<article class="trait"><div class="trait-head"><span>0${i+1} / ${d.name}</span><b>${esc(d.display)}</b></div><div class="trait-track" role="img" aria-label="${esc(d.display)}">${d.value===null?'<span class="trait-no-data">等待更多记录</span>':`<i style="left:${Math.max(0,Math.min(100,d.value*100))}%"></i>`}</div><div class="trait-poles"><span>${d.left}</span><span>${d.right}</span></div><p>${d.reading}</p><details><summary>为什么这样判断？</summary><p>${d.evidence}</p></details></article>`).join('')}</div><div class="mirror-grid"><article><span>你可以保留的习惯</span><h3>${esc(a.role.strength)}</h3></article><article><span>下次值得留意的盲点</span><h3>${esc(a.role.blindspot)}</h3></article></div><details class="report-method"><summary>风格称号与代号的计算规则</summary><p>这是本次演练的游戏化行为标签，不是MBTI或心理测评，也不判断长期投资能力。C/P：平均基金仓位低于/不低于50%；F/M：最大单基金占比均值不低于/低于65%；A/W：有已成交决策的日期占比不低于/低于30%；R/O：主动笔记日期占比不低于/低于20%。没有买入时为WAIT。代号各端都没有“优秀/差劲”的含义。</p></details>`;
 const c3=`${heading(3,'是谁，改写了你的结局？','把每只基金的持仓变化、卖出收入、分红与费用放回账本。')}${a.contributors.length?`<div class="reveal-insight"><span>本局最大净贡献</span><h3>${esc(top.name)}</h3><strong class="${tone(top.profit)}">${signed(top.profit)}</strong><p>${top.profit>0?'它是本次净盈亏贡献最高的基金。':top.profit<0?'所有已交易基金均为负贡献；这一只的亏损最少。':'它的净贡献接近零。'}${bottom!==top&&bottom.profit<0?` 最大负贡献来自${esc(bottom.name)}（${signed(bottom.profit)}）。`:''}</p></div><div class="attribution-list">${a.contributors.map(c=>`<div class="attribution-row"><div><b>${esc(c.name)}</b><small>${c.code} · ${c.units>1e-6?'仍有持仓':'已退出'}</small></div><div class="contribution-track"><i class="${tone(c.profit)}" style="width:${Math.max(1,Math.abs(c.profit)/largest*100)}%"></i></div><strong class="${tone(c.profit)}">${signed(c.profit)}</strong><details><summary>查看账本</summary><p>买入总支出 ¥${money(c.bought)}；卖出净收入 ¥${money(c.sold)}；现金分红 ¥${money(c.dividends)}；期末持仓市值 ¥${money(c.value)}；已付费用 ¥${money(c.fees)}。</p></details></div>`).join('')}</div><p class="report-footnote">净贡献 = 卖出净收入 + 现金分红 + 当前持仓市值 − 买入支出。费用已包含在买入支出与卖出净收入内，不重复扣除。全部基金贡献之和与账户盈亏核对，含未实现浮盈亏；它不是对基金未来好坏的评价。</p>`:`<div class="report-empty"><span>◌</span><h3>${a.reconciled?'这一次，现金也是主角。':'收益拆解暂未完成核对'}</h3><p>${a.reconciled?'没有成交，就没有可归因给基金的盈亏。你的结果仍然是一份有效的观察记录。':'账户总收益仍然可见；暂不展示未核对的基金贡献。'}</p></div>`}<div class="cost-receipt"><span>这一局，你为交易付出了</span><b>¥${money(p.fees)}</b><span>占初始本金 ${(a.feeDrag*100).toFixed(3)}% · ${a.filledCount}笔成交</span></div>`;
 const alt=a.alternate;
 const c4=`${heading(4,'如果第一笔之后，你只是等下去？','这是可复算的平行路线，不是事后挑出的最佳答案。')}${alt?`<div class="parallel-paths"><article class="actual-path"><span>你真正走过的路线</span><strong>${pct(p.return)}</strong><p>最终/当前资产 ¥${money(p.total)}</p><small>${a.filledCount} 笔成交 · 已付费用 ¥${money(p.fees)}</small></article><article><span>第一笔买入后，不再交易</span><strong>${pct(alt.return)}</strong><p>同一截止时点 ¥${money(alt.total)}</p><small>保留第一笔份额与剩余现金，分红现金入账</small></article></div><div class="parallel-answer"><b>${Math.abs(alt.difference)<.01?'两条路线目前几乎重合。':`你的实际路线比这条固定路线${alt.difference>0?'多':'少'}了 ¥${money(Math.abs(alt.difference))}。`}</b><p>基于 ${alt.date} 的第一笔：${esc(alt.name)}，买入支出 ¥${money(alt.amount)}。比较会同时包含之后的投入规模、基金选择、买卖时机和费用差异，不能只归因于某一次操作。</p></div><details class="report-method"><summary>平行路线怎么算？</summary><p>初始本金减去第一笔买入支出，保留第一笔实际获得的份额，按截止时点已知净值估值，加上此后该份额应得的现金分红。保留第一笔申购费，忽略所有后续订单；两条路线均不强制清仓、不预扣未来赎回费。只计算已经走过的日子，不使用未来行情。</p></details>`:`<div class="report-empty"><span></span><h3>第一笔尚未发生，岔路还没有展开。</h3><p>有买入成交后，这里会把你的实际路线，与“只保留第一笔”的固定路线放在一起。无需为了生成报告而交易。</p></div>`}<div class="cash-alternate"><span>另一条已知路线：始终持有现金</span><b>0.00% · ¥${money(r.initial)}</b><small>按本演练现金不计息的假设。</small></div>`;
 const c5=`${heading(5,'有些日子，值得再看一次。','先还原发生了什么，再判断自己当时为什么这样做。')}<div class="story-timeline">${a.moments.map((m,i)=>`<article><div class="moment-pin">${String(i+1).padStart(2,'0')}</div><time>${m.date}</time><h3>${esc(m.title)}</h3><p>${esc(m.body)}</p>${m.quote?`<blockquote>“${esc(m.quote)}”</blockquote>`:''}</article>`).join('')||'<div class="report-empty"><h3>故事还在等待第一条记录。</h3><p>不交易也可以写下今天为什么继续等待。</p></div>'}</div>`;
 const c6=`${heading(6,'把这一局，变成下一局的起点。','成就记录你做过什么，练习任务帮助你检验下一次的判断。')}<div class="badge-heading"><b>${earned} / ${a.badges.length} 枚本局成就</b><span>不是玩家排名，不评价收益能力</span></div><div class="achievement-grid">${a.badges.map(b=>`<article class="achievement ${b.earned?'earned':''}"><span aria-hidden="true">${b.icon}</span><h3>${b.name}</h3><b>${b.earned?'已记录':'尚未达成'}</b><p>${esc(b.reason)}</p></article>`).join('')}</div><h3 class="mission-heading">选一个值得带走的小实验</h3><div class="mission-grid">${a.missions.map((m,i)=>`<article><span>QUEST 0${i+1}</span><h3>${m.title}</h3><p>${m.body}</p><button data-report-mission="${i}">加入我的复盘</button></article>`).join('')}</div><p class="report-footnote">一局${r.duration||30}天只能描述一次经历。称号、成就和目标都是游戏规则；没有人群排名、心理诊断或对未来收益的保证。</p>`;
 const chapters=[c1,c2,c3,c4,c5,c6];
 return `<div class="review-screen" id="rehearsalReport"><div class="report-topline"><div><span class="eyebrow">THE REHEARSAL CHRONICLE</span><p>${r.start} — ${r.date} · ${r.completed?'完整复盘':'阶段复盘'}</p></div><div class="report-actions"><button id="expandReport">展开完整报告</button><button id="printReport">打印 / 保存PDF</button><button id="exportRun">导出数据</button></div></div>${hero}<nav class="chapter-nav" aria-label="复盘章节">${chapterNames.map((name,i)=>`<button data-chapter="${i+1}" class="${i<revealed?'revealed':''}"><span>0${i+1}</span>${name}</button>`).join('')}</nav><p class="chapter-progress" aria-live="polite">已展开 ${revealed} / 6 章 · 每一条结论都有计算依据</p>${chapters.map((content,i)=>`<section class="report-chapter" id="reportChapter${i+1}" ${i>=revealed?'hidden':''}>${content}</section>`).join('')}<div class="next-chapter" ${revealed>=6?'hidden':''}><span>接下来，你会看到</span><h3>${chapterNames[Math.min(revealed,5)]}</h3><button id="nextReportChapter" class="primary">继续翻开下一章 →</button><p>完整内容均可阅读</p></div></div>`;
}
