import {sizeTradeDock} from '../trade-dock.js';
import {reportMarkup,reportChart} from './report-view.js';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>Number(n).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2}),pct=n=>(n>=0?'+':'')+(n*100).toFixed(2)+'%',levels=['基础','进阶','挑战'],phases={watch:'观察中',pending:'首次突破',confirmed:'已确认突破',exited:'退出／复核',failed:'突破未确认',unknown:'数据待核实'};
let selectedDuration=90,holdingWindow='90';
const periodLabel=d=>d===365?'1年':d+'天';
let meta,view=null,selectedDate='2024-09-02',selectedLevel=1,capital=100000,preview=null,calendar=[],month='2024-09',tab='funds',search='',kind='',onlyMatch=true,sort='change',pageSize=24,busy=false,previewToken=0;
const modal=$('modal');
const reportReveals=new Map();
function toast(message,error=false){const el=$('toast');el.textContent=message;el.className=error?'error-toast':'';el.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.hidden=true,4500)}
async function api(path,body){let response;try{response=await fetch('/api/sim/'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined})}catch{throw Error('无法连接演练服务，操作结果尚未确认。请恢复连接并重新载入存档后继续。')}let result;try{result=await response.json()}catch{throw Error('服务暂不可用，请稍后重试')}if(!response.ok)throw Error(result.error||'请求失败');return result}
function showModal(html,wide=false){$('modalContent').innerHTML=html;modal.classList.toggle('wide-dialog',wide);if(!modal.open)modal.showModal()}
document.querySelector('.modal-close').onclick=()=>modal.close();
function curve(points,color='#b9e38a',height=130,second=null){if(!points?.length)return '';const vals=points.map(p=>p[1]),all=second?vals.concat(second.map(p=>p[1])):vals,lo=Math.min(...all),hi=Math.max(...all),span=hi-lo||Math.max(hi*.01,1),x=i=>12+i*576/Math.max(1,points.length-1),y=v=>height-20-(v-lo)*(height-40)/span;const line=arr=>arr.map((p,i)=>`${x(i)},${y(p[1])}`).join(' ');return `<svg viewBox="0 0 600 ${height}" role="img" aria-label="已披露历史走势，${esc(points[0][0])}至${esc(points.at(-1)[0])}" preserveAspectRatio="none"><path d="M12 ${height-20}H588" stroke="${color}" opacity=".15"/>${second?`<polyline points="${line(second)}" fill="none" stroke="#94a5b8" stroke-width="2" stroke-dasharray="5 5"/>`:''}<polyline points="${line(points)}" fill="none" stroke="${color}" stroke-width="3" stroke-linejoin="round"/><circle cx="${x(points.length-1)}" cy="${y(vals.at(-1))}" r="4" fill="${color}"/></svg>`}
function eventCards(m){return `<div class="section-title"><div><h2>当时，世界正在发生什么</h2><p>截至 ${m.date} 09:00（北京时间）可见的精选事件 · 机制解读不等于走势预测</p></div></div><div class="events">${m.events.length?m.events.map(e=>`<article class="event ${e.available===m.date?'new-event':''}">${e.available===m.date?'<span class="pill orange">今日新公开</span> ':''}<time>${e.published} 公开 · ${e.available} 起可见</time> <span class="pill">${esc(e.category)}</span><h3>${esc(e.title)}</h3><p class="fact"><b>已知事实</b> · ${esc(e.fact)}</p><details><summary>如何影响中国市场？</summary><p><b>可能的传导路径</b> · ${esc(e.impact)}</p><p><b>当时仍未知</b> · ${esc(e.uncertainty)}</p></details><a href="${esc(e.source)}" target="_blank" rel="noopener">查看原始来源</a></article>`).join(''):'<div class="empty">此日期之前，精选事件库尚无收录。未收录不代表当时没有重要事件。</div>'}</div><p class="data-note">事件库为人工核验的精选档案，并非完整新闻流。仅按已知公开日期展示；缺少精确发布时间的国内事件保守地从次日开放。较早的事件会保留其原始日期，不能视为当日新消息。</p>`}
function marketCard(m,full=false){return `<div class="market-panel panel"><div class="panel-head"><span class="eyebrow">MARKET SNAPSHOT / ${m.asof}</span><span class="pill lime">规则判断</span></div><h2>${esc(m.label)}</h2><div class="market-badges"><span class="pill">情绪 ${m.sentiment}</span><span class="pill">波动 ${m.volatility}</span><span class="pill">${m.positive}/3 指数近20日上涨</span></div><div class="index-grid">${m.indices.map(i=>`<div class="index-item">${i.name}<b>${pct(i.r20)}</b><small>近20个交易日</small></div>`).join('')}</div><div class="market-chart">${curve(m.indices[0].chart)}</div><p class="small muted">沪深300 · 最近60个已披露交易日 · 截止 ${m.asof}</p><details class="market-explain" ${full?'open':''}><summary>为什么这样判断？</summary><p>${esc(m.basis)}</p><p>沪深300收盘 ${m.indices[0].close.toFixed(2)}；20日均线 ${m.indices[0].ma20.toFixed(2)}；60日均线 ${m.indices[0].ma60.toFixed(2)}；20日收益波动折算年化 ${(m.indices[0].vol*100).toFixed(1)}%。</p><p>“强势／偏弱”是当时价格指标的标签，不是对牛熊市的事后定性。情绪不是新闻情感调查。数据来源：<a href="https://gu.qq.com/sh000300" target="_blank" rel="noopener">腾讯证券指数行情</a></p></details></div>`}
function compositionPreview(f){
 const c=f.composition;
 if(!c||c.status!=='available')return `<div class="composition empty-composition"><span class="composition-label">持仓构成</span><p>${esc(c?.message||'此日期之前尚无已核验的持仓报告')}</p>${c?.period?`<small>报告期 ${c.period}</small>`:''}</div>`;
 const items=c.funds.length?c.funds:((f.type.includes('债券')&&c.bonds.length)||!c.stocks.length)?c.bonds:c.stocks;
 const label=c.funds.length?'持有的基金':items===c.bonds?'主要债券':'重仓股票';
 return `<div class="composition"><div class="composition-heading"><span class="composition-label">${label}</span><span>${c.period}</span></div><ul>${items.slice(0,3).map(h=>`<li><span title="${esc(h.name)}">${esc(h.name)}</span><b>${h.weight===null?'未披露':h.weight.toFixed(2)+'%'}</b></li>`).join('')}</ul><div class="composition-bottom"><span>占基金净值 · 定期披露</span><button data-composition="${f.code}">查看构成</button></div>${c.isLink?'<p class="composition-hint">ETF联接 · 不穿透目标ETF持仓</p>':''}</div>`;
}
function showComposition(code){
 const f=view.funds.find(f=>f.code===code),c=f.composition;
 const sections=[['持有的基金',c.funds],['前十大直接股票持仓',c.stocks],['前五大债券持仓',c.bonds]];
 showModal(`<div class="eyebrow">PORTFOLIO / 当时已披露的构成</div><h2>${esc(f.name)}</h2><p class="data-note">报告期末 ${c.period} · 公布 ${c.published}<br>从 ${c.available} 起在演练中可见；当前演练日期 ${view.run.date}。</p>${sections.filter(([,rows])=>rows.length).map(([title,rows])=>`<section class="composition-detail"><h3>${title}</h3><div class="holdings-table"><div class="holdings-row holdings-header"><span>名称 / 代码</span><span>占基金净值</span></div>${rows.map(h=>`<div class="holdings-row"><span>${esc(h.name)}${h.code?`<small>${esc(h.code)}</small>`:''}</span><b>${h.weight===null?'未披露':h.weight.toFixed(2)+'%'}</b></div>`).join('')}</div></section>`).join('')}<p class="data-note">以上是报告期末的部分持仓，不是当天实时持仓，也不是完整资产配置；未列出部分可能包含其他证券、现金等，不能全部当作现金。股票、债券和基金占比均以基金资产净值为分母，不将各组强行凑成100%。${c.isLink?'联接基金主要通过目标ETF投资；这里不把目标ETF的股票当作本基金直接持仓。':''}</p><div class="composition-sources"><a href="${esc(c.source)}" target="_blank" rel="noopener">季度报告原文</a><a href="${esc(c.holdingsSource)}" target="_blank" rel="noopener">股票持仓来源</a><a href="${esc(c.bondSource)}" target="_blank" rel="noopener">债券持仓来源</a></div>`);
}
function limitations(){return `<details class="data-note"><summary>数据范围、交易假设与存档说明</summary><p>可选起点 ${meta.startMin}—${meta.startMax}，每次可选30、90、180或365个自然日。${meta.fundCount}只净值完整的历史基金样本，覆盖股票、指数、混合与债券；不代表支付宝当时可购买清单。${esc(meta.limitations)}</p><p>${esc(meta.assumptions)} 不模拟税费差异、最低持有期、历史限购和真实订单拒绝。净值来源：<a href="https://fund.eastmoney.com/" target="_blank" rel="noopener">天天基金</a>。持仓按季度报告披露日期匹配，缺少精确发布时间时从次日可见；展示部分重仓证券，缺失明确标注，不用今天的持仓替代。</p><p>每天固定在北京时间09:00决策，仅展示日期早于当天的净值；历史披露精确时刻未复原，采用境内基金次日可见的教学假设。当日下单先冻结资金或份额，“下一天”后才能看到成交净值；周末及休市日顺延。目标为游戏初始参数，未经历史成功率校准，不是收益预测。</p><p>进度保存在服务端，并通过当前浏览器的匿名身份恢复，无需登录。不支持跨设备恢复；清除网站Cookie后将失去访问原存档的身份。可在复盘中导出记录。</p></details>`}
async function loadPreview(){meta.startMax=meta.startMaxByDuration?.[selectedDuration]||meta.startMax;if(selectedDate>meta.startMax)selectedDate=meta.startMax;const token=++previewToken;try{const result=await Promise.all([api('preview?date='+selectedDate+'&duration='+selectedDuration),api('calendar?date='+selectedDate+'&duration='+selectedDuration)]);if(token!==previewToken)return;[preview,{days:calendar}]=result;month=selectedDate.slice(0,7);renderSetup()}catch(e){toast(e.message,true)}}
function renderSetup(){view=null;document.querySelector('.end-day')?.remove();const first=month+'-01',weekday=(new Date(first+'T00:00:00Z').getUTCDay()+6)%7,monthDays=new Date(+month.slice(0,4),+month.slice(5,7),0).getDate(),map=new Map(calendar.map(d=>[d.date,d]));$('app').innerHTML=`<div class="page-intro enter"><div><div class="eyebrow">MANUAL REHEARSAL / 手动历史演练</div><h1>回到那一天。<br>这次，由你决定。</h1><p>先理解当时的市场，再用筛选策略寻找候选。买入、等待、退出，一天一天练习自己的判断。</p></div><div class="step-track"><span class="current">01 选择起点</span>—<span>02 每日决策</span>—<span>03 复盘</span></div></div>
${meta.runs.find(r=>!r.completed)?`<div class="market-strip"><p>你还有一场未结束的演练：${meta.runs.find(r=>!r.completed).start} 开始</p><button data-resume="${meta.runs.find(r=>!r.completed).id}">继续上次演练</button></div>`:''}
<div class="setup-grid"><section class="panel calendar-panel"><div class="panel-head"><h2>选择你的起点</h2><span class="pill blue">${selectedDuration}个自然日</span></div><div class="calendar-top"><button id="prevMonth" aria-label="上个月" ${month<=meta.startMin.slice(0,7)?'disabled':''}>‹</button><label><span class="small">历史日期</span><input id="startDate" type="date" min="${meta.startMin}" max="${meta.startMax}" value="${selectedDate}"></label><button id="nextMonth" aria-label="下个月" ${month>=meta.startMax.slice(0,7)?'disabled':''}>›</button></div><div class="week">${['一','二','三','四','五','六','日'].map(s=>`<span>${s}</span>`).join('')}</div><div class="calendar">${'<span></span>'.repeat(weekday)}${Array.from({length:monthDays},(_,i)=>{const date=month+'-'+String(i+1).padStart(2,'0'),d=map.get(date);return `<button data-date="${date}" class="${d?.regime||''} ${date===selectedDate?'selected':''}" ${d?'':'disabled'} aria-label="${date} ${d?.label||'不可用'}" aria-pressed="${date===selectedDate}">${i+1}${d?.events?'<span class="event-mark">•</span>':''}</button>`}).join('')}</div><div class="legend">${[['strong','强势'],['rising','温和'],['range','震荡'],['weak','偏弱']].map(([a,b])=>`<span><i class="${a}"></i>${b}</span>`).join('')}</div><p class="calendar-note small muted">颜色根据该日期之前的指数数据判断。圆点表示当日起可见的已收录事件。开局后可以按日、周或30天向前。</p></section>${marketCard(preview)}
<section class="panel challenge-panel"><div><div class="eyebrow">YOUR STARTING POINT</div><h2>设定这次练习</h2><label style="margin-top:16px">演练期限<select id="durationSelect">${[30,90,180,365].map(d=>`<option value="${d}" ${d===selectedDuration?'selected':''}>${periodLabel(d)}</option>`).join('')}</select></label><label style="margin-top:16px">初始虚拟资金（元）<input id="capital" type="number" min="1000" max="100000000" step="1000" value="${capital}"></label></div><div><p class="small muted" style="margin-bottom:10px">${preview.label} · 目标按开局环境锁定</p><div class="level-grid">${levels.map((l,i)=>`<button class="level ${i===selectedLevel?'selected':''}" data-level="${i}" aria-pressed="${i===selectedLevel}">${l}<b>${pct(preview.targets[i])}</b><small>${selectedDuration}天账户收益目标</small></button>`).join('')}</div></div><div class="launch-row"><p>净收益按已发生费用扣除后的账户市值计算。保留现金也是一种决定。<br>教学费率与成交假设见下方说明；目标不会随之后的行情改变。</p><button id="startRun" class="primary">开启${periodLabel(selectedDuration)}演练 <span></span></button></div></section></div><section class="event-section">${eventCards(preview)}</section>${limitations()}`;
 $('startDate').onchange=e=>{if(e.target.value>=meta.startMin&&e.target.value<=meta.startMax){selectedDate=e.target.value;loadPreview()}else toast('请选择可用日期',true)};
 for(const [id,n] of [['prevMonth',-1],['nextMonth',1]])$(id).onclick=()=>{const d=new Date(month+'-15T00:00:00Z');d.setUTCMonth(d.getUTCMonth()+n);selectedDate=d.toISOString().slice(0,7)+'-01';if(selectedDate<meta.startMin)selectedDate=meta.startMin;loadPreview()};
 document.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>{capital=Number($('capital').value);selectedDate=b.dataset.date;loadPreview()});
 document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{capital=Number($('capital').value);selectedLevel=+b.dataset.level;renderSetup()});
 $('durationSelect').onchange=e=>{capital=Number($('capital').value);selectedDuration=+e.target.value;loadPreview()};
 $('capital').oninput=e=>capital=Number(e.target.value);$('startRun').onclick=startRun;bindResume();
}
async function startRun(){if(busy)return;busy=true;document.body.classList.add('busy');try{capital=Number($('capital').value);view=await api('start',{id:crypto.randomUUID(),date:selectedDate,capital,level:selectedLevel,duration:selectedDuration});history.replaceState(null,'','/simulation.html?run='+view.run.id);tab='funds';renderRun();toast('演练已开始。今天的成交价格尚未揭晓。')}catch(e){toast(e.message,true)}finally{busy=false;document.body.classList.remove('busy')}}
async function act(input){if(busy)return false;busy=true;document.body.classList.add('busy');try{view=await api('action',{id:view.run.id,version:view.run.version,actionId:crypto.randomUUID(),...input});if(view.run.completed)tab='review';renderRun();return true}catch(e){toast(e.message,true);return false}finally{busy=false;document.body.classList.remove('busy')}}
function redemptionPanel(r,p){
 const pending=[...r.receivables].sort((a,b)=>(a.date||'9999').localeCompare(b.date||'9999'));
 if(!pending.length)return r.settlementDate?`<section class="settlement-panel"><b>赎回款已全部到账</b><p>到账进度截至 ${r.settlementDate}；本局成绩仍按 ${r.date} 的估值锁定。到账只是待收款转为现金，不增加收益。</p></section>`:'';
 const next=pending.find(c=>c.date)?.date;
 return `<section class="settlement-panel" aria-label="赎回到账进度"><div class="settlement-heading"><div><span class="eyebrow">REDEMPTION / 到账进度</span><h3>¥${money(p.receivable)} 待转入可用现金</h3></div>${r.completed&&next?`<button id="settleFunds" class="dark-btn">推进到账至 ${next}</button>`:''}</div><p>${r.completed?`${r.duration||30}天交易已结束，仍可推进赎回到账。成绩与持仓估值固定在 ${r.date}，不会延长挑战。`:'按卖出成交后的第2个交易日到账，周末和节假日顺延。点击“下一天”推进演练日期，到期自动转入可用现金。'}</p><ul>${pending.map(c=>{const o=r.orders.find(o=>o.id===c.orderId);return `<li><span>${esc(o?.name||'赎回款')}<small>${o?.filled||'—'} 卖出成交</small></span><b>¥${money(c.amount)}</b><span>${c.date?`${c.date} 09:00 到账`:'到账日期待核实'}</span></li>`}).join('')}</ul></section>`;
}
function renderRun(){const {run:r,portfolio:p,market:m}=view;$('app').innerHTML=`<div class="run-heading enter"><div><div class="eyebrow">${r.completed?'REHEARSAL COMPLETE':'YOUR DECISIONS, ONE DAY AT A TIME'}</div><h1>${r.completed?'本次演练已结束':r.date} <span class="pill ${view.isTrading?'lime':'blue'}">${r.completed?(r.duration||30)+'天复盘':view.isTrading?'交易日 · 09:00':'休市日 · 09:00'}</span></h1><div class="day-counter">${r.start} → ${r.end} · ${r.completed?'已完成':`第 ${r.elapsed+1} / ${r.duration||30} 天`} · 北京时间 · <span class="saved">进度已保存</span></div></div><button id="newRun" class="quiet">新建演练</button></div>
<div class="dashboard"><section class="panel account"><div class="panel-head"><span class="eyebrow">TOTAL ASSETS / 总资产</span><span class="pill">虚拟资金</span></div><div class="total">¥ ${money(p.total)}</div><div class="account-stats"><div><strong>${pct(p.return)}</strong><span>账户收益</span></div><div><strong>${pct(p.benchmark)}</strong><span>同期沪深300 · 价格收益</span></div><div><strong>${(p.drawdown*100).toFixed(2)}%</strong><span>最大回撤</span></div></div><div class="mini-balances"><div>可用现金<b>¥ ${money(p.cash)}</b></div><div>基金市值<b>¥ ${money(p.held)}</b></div><div>冻结 / 待到账<b>¥ ${money(p.pending+p.receivable)}</b></div></div></section><section class="panel challenge-live"><div class="panel-head"><h3>${levels[r.level]}挑战</h3><span class="pill">开局：${r.openingRegime}</span></div><div class="target">${pct(r.target)} <span class="small muted">目标已锁定</span></div><p class="small muted">${r.target===0?'本关练习保护本金，持有现金也可以达标。':`距离目标 ${pct(Math.max(0,r.target-p.return))} · ${r.completed?'已结算':`还剩 ${(r.duration||30)-r.elapsed} 天`}`}</p><div class="progress-track"><i style="width:${r.elapsed/(r.duration||30)*100}%"></i></div><p class="small muted">${r.elapsed}/${r.duration||30} 天 · 累计已付费用 ¥${money(p.fees)}</p><p class="small muted" style="margin-top:16px">${r.completed?'已按截止日可见净值估值；未强制卖出持仓。':'收益目标是练习参数，不是预测。避免为了通关强行交易。'}</p></section></div>
${redemptionPanel(r,p)}<div class="market-strip"><div><b>${m.label}</b> <span class="pill">${m.sentiment}</span><p>信息截止 ${m.asof} · 波动${m.volatility}${m.events.find(e=>e.available===r.date)?' · 今天有新事件开放':''}</p></div><button id="marketDetails">查看市场档案</button></div>
${r.completed?`<div class="report-banner"><div class="eyebrow">${r.duration||30} DAYS / 你的决策记录</div><h2>${p.return+1e-10>=r.target?'本次达到收益目标':'本次未达到收益目标'}</h2><p>${r.orders.some(o=>o.status==='filled')?'把结果与当时的理由放在一起看，才知道下一次要改什么。':'本次没有成交，记录为现金防守演练。'}</p></div>`:''}
<div class="trading-layout"><section class="decision-workspace"><div class="tabs" role="tablist">${[['funds','候选基金'],['holdings','我的持仓'],['orders','交易订单'],['review','复盘日志']].map(([id,name])=>`<button role="tab" aria-selected="${tab===id}" class="${tab===id?'active':''}" data-tab="${id}">${name}${id==='holdings'?' · '+p.holdings.length:''}${id==='orders'?' · '+r.orders.filter(o=>o.status==='queued').length:''}</button>`).join('')}</div><div id="workspace"></div></section><aside class="live-events" aria-label="当前演练日的市场事件"><div class="live-events-status"><span class="pill lime">随演练日期更新</span><span>${m.events.filter(e=>e.available===r.date).length} 条今日新公开</span></div>${eventCards(m)}</aside></div>${limitations()}`;
 document.querySelector('.end-day')?.remove();if(!r.completed){const bar=document.createElement('div');bar.className='end-day';bar.innerHTML=`<div><div class="trade-dock-balances"><span>可用现金<b>¥${money(p.cash)}</b></span><button type="button" data-dock-tab="holdings">持仓 · ${p.holdings.length}<b>¥${money(p.held)}</b></button><button type="button" data-dock-tab="orders">待成交<b>${r.orders.filter(o=>o.status==='queued').length} 笔</b></button></div><p>${view.isTrading?'今天的决定，准备好了吗？':'今天休市，也可以继续等待。'}<br><span>${r.orders.filter(o=>o.status==='queued').length} 笔待成交 · ${p.receivable?money(p.receivable)+'元待到账 · '+(r.receivables.map(c=>c.date).filter(Boolean).sort()[0]||'日期待核实'):'资金与净值逐日结算'}</span></p><label class="advance-pause"><input id="pauseAdvance" type="checkbox" checked>到账、市场事件或持仓信号变化时暂停</label></div><div class="advance-buttons"><button data-advance="1" class="primary">下一天 →</button><button data-advance="7">下一周</button><button data-advance="30">推进30天</button></div>`;document.body.append(bar);sizeTradeDock(bar);bar.querySelectorAll('[data-dock-tab]').forEach(b=>b.onclick=()=>{document.querySelector('[data-tab="'+b.dataset.dockTab+'"]')?.click();document.querySelector('.tabs')?.scrollIntoView({behavior:'smooth',block:'start'});});bar.querySelectorAll('[data-advance]').forEach(button=>button.onclick=async()=>{const journalCount=view.run.journal.length;if(await act({type:'advance',days:+button.dataset.advance,pause:$('pauseAdvance').checked})){const received=view.run.journal.slice(journalCount).filter(j=>j.type==='settle').reduce((sum,j)=>sum+j.amount,0),a=view.run.advanceSummary;toast(received>0?'赎回款 ¥'+money(received)+' 已到账':`已推进 ${a.advanced} 天 · ${a.reason}`)}})}
 if($('settleFunds'))$('settleFunds').onclick=async()=>{const before=view.portfolio.cash;if(await act({type:'settle'}))toast('赎回款 ¥'+money(view.portfolio.cash-before)+' 已到账；本局成绩保持不变。')};
 $('newRun').onclick=async()=>{meta=await api('bootstrap');history.replaceState(null,'','/simulation.html');await loadPreview()};$('marketDetails').onclick=()=>showModal(marketCard(m,true)+`<section class="event-section">${eventCards(m)}</section>`,true);
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;renderWorkspace();document.querySelectorAll('[data-tab]').forEach(x=>{x.classList.toggle('active',x.dataset.tab===tab);x.setAttribute('aria-selected',x.dataset.tab===tab)})});renderWorkspace();
}
function renderWorkspace(){const {run:r,portfolio:p}=view;document.querySelector('.trading-layout')?.classList.toggle('report-layout',tab==='review');
 if(tab==='funds'){
  $('workspace').innerHTML=`<section class="rule-bar"><div class="rule-controls"><b>筛选策略</b><label class="check-label"><input id="rule1" type="checkbox" ${r.rules.enabled.includes('rule1')?'checked':''} ${r.completed?'disabled':''}>规则一 · 横盘</label><label class="check-label"><input id="rule2" type="checkbox" ${r.rules.enabled.includes('rule2')?'checked':''} ${r.completed?'disabled':''}>规则二 · 突破确认</label><span class="small muted">多选取交集 · 不会自动买卖</span></div><details><summary>调整参数与信号阶段</summary><div class="rule-settings"><label>自然日期间<select id="ruleDays">${[7,15,30].map(v=>`<option ${r.rules.days===v?'selected':''}>${v}</option>`).join('')}</select></label><label>振幅上限 %<input id="ruleAmp" type="number" value="${r.rules.amp}" min="0" max="1000"></label><label>涨跌最低 %<input id="ruleMin" type="number" step="any" value="${r.rules.min??''}" placeholder="不限"></label><label>涨跌最高 %<input id="ruleMax" type="number" step="any" value="${r.rules.max??''}" placeholder="不限"></label><label>突破阶段<select id="ruleStage">${[['confirmed','已确认突破'],['newBuy','本次新确认'],['pending','首次突破待确认'],['exited','退出／复核']].map(([v,t])=>`<option value="${v}" ${r.rules.stage===v?'selected':''}>${t}</option>`).join('')}</select></label></div><p class="small muted" style="margin-top:12px">规则一使用截至最近已披露净值日的自然日窗口。规则二固定使用突破前15个自然日、10%振幅与±5%涨跌，锁定区间后连续两点确认。参数修改会写入复盘日志。</p></details><button id="applyRules" class="quiet" style="margin-top:12px" ${r.completed?'disabled':''}>应用筛选策略</button></section><div class="filters"><label class="search">搜索基金<input id="fundSearch" placeholder="名称或代码" value="${esc(search)}"></label><label>类型<select id="fundKind"><option value="">全部类型</option>${['股票','指数','混合','债券'].map(t=>`<option ${kind===t?'selected':''}>${t}</option>`).join('')}</select></label><label>结果<select id="fundResult"><option value="match" ${onlyMatch?'selected':''}>符合已选策略</option><option value="all" ${!onlyMatch?'selected':''}>全部历史基金</option></select></label><label>排序<select id="fundSort"><option value="change" ${sort==='change'?'selected':''}>涨跌幅从高到低</option><option value="amp" ${sort==='amp'?'selected':''}>振幅从小到大</option></select></label></div><p id="fundCount" class="small muted" style="margin-bottom:14px"></p><div id="fundList" class="funds"></div><button id="loadMore" class="quiet wide" style="margin-top:16px">显示更多基金</button>`;
  $('applyRules').onclick=()=>act({type:'rules',rules:{enabled:['rule1','rule2'].filter(id=>$(id).checked),days:+$('ruleDays').value,amp:+$('ruleAmp').value,min:$('ruleMin').value===''?null:+$('ruleMin').value,max:$('ruleMax').value===''?null:+$('ruleMax').value,stage:$('ruleStage').value}});
  $('fundSearch').oninput=e=>{search=e.target.value;pageSize=24;renderFunds()};$('fundKind').onchange=e=>{kind=e.target.value;pageSize=24;renderFunds()};$('fundResult').onchange=e=>{onlyMatch=e.target.value==='match';pageSize=24;renderFunds()};$('fundSort').onchange=e=>{sort=e.target.value;renderFunds()};$('loadMore').onclick=()=>{pageSize+=24;renderFunds()};renderFunds();
 }else if(tab==='holdings'){
  $('workspace').innerHTML=p.holdings.length?`<div class="holdings-heading"><h2>我的持仓</h2><span class="pill">走势图期间</span><select id="holdingWindow" aria-label="持仓走势图期间">${[['30','近1个月'],['90','近3个月'],['180','近6个月'],['held','持有以来']].map(([v,t])=>`<option value="${v}" ${holdingWindow===v?'selected':''}>${t}</option>`).join('')}</select></div><div class="holdings-cards">${p.holdings.map(h=>{const f=view.funds.find(f=>f.code===h.code),cutoff=holdingWindow==='held'?h.firstHeld:new Date(Date.parse(r.date+'T00:00:00Z')-Number(holdingWindow)*86400000).toISOString().slice(0,10),points=(h.history||f?.chart||[]).filter(p=>p[0]>=cutoff),change=points.length>=2?points.at(-1)[1]/points[0][1]-1:null;return `<article class="holding-card"><header><div><h3>${esc(h.name)}</h3><span class="small muted">${h.code}</span></div><button data-sell="${h.code}" ${!h.available||r.completed?'disabled':''}>卖出</button></header><div class="holding-stats"><div><span>持仓市值</span><strong>¥${money(h.value)}</strong><small>买入成本 ¥${money(h.cost)}</small></div><div><span>持仓浮动盈亏</span><strong class="${h.change>=0?'positive':'negative'}">${pct(h.change)}</strong><small>${h.value-h.cost>=0?'+':'−'}¥${money(Math.abs(h.value-h.cost))}</small></div></div><div class="holding-trend"><div class="holding-trend-label"><span>${holdingWindow==='held'?'持有以来':'最近 '+holdingWindow+' 个自然日'} · 基金走势</span><b>${change===null?'数据不足':pct(change)}</b></div>${points.length>=2?curve(points,change>=0?'#117661':'#b05b46',120):'<p class="data-note">此期间不足两个已披露净值点，暂不能绘制趋势。</p>'}<div class="holding-chart-dates"><span>${points[0]?.[0]||'—'}</span><span>${points.at(-1)?.[0]||'—'}</span></div></div><div class="holding-details"><div><span>份额 / 可卖</span><b>${h.units.toFixed(4)} / ${h.available.toFixed(4)}</b><small>待确认 ${h.locked.toFixed(4)} · 卖出冻结 ${h.reserved.toFixed(4)}</small></div><div><span>参考净值</span><b>${h.nav.toFixed(4)}</b><small>披露日期 ${h.navDate}</small></div></div></article>`}).join('')}</div><p class="data-note">走势图使用上方所选期间，按现金分红调整，仅含演练当日之前已披露的净值；区间涨跌幅不等于你的持仓收益。持仓浮动盈亏按剩余买入成本计算，未加回已入账的现金分红，账户总收益包含分红。赎回款按预计日期到账。</p>`:'<div class="empty">还没有持仓。你可以从候选基金中选择，也可以继续持有现金。</div>';
  if($('holdingWindow'))$('holdingWindow').onchange=e=>{holdingWindow=e.target.value;renderWorkspace()};
  document.querySelectorAll('[data-sell]').forEach(b=>b.onclick=()=>trade(b.dataset.sell,'sell'));
 }else if(tab==='orders'){
  $('workspace').innerHTML=r.orders.length?`<div class="table-wrap"><table><thead><tr><th>订单</th><th>状态</th><th>金额 / 份额</th><th>成交信息</th><th>操作</th></tr></thead><tbody>${[...r.orders].reverse().map(o=>`<tr><td><b>${o.side==='buy'?'买入':'卖出'} ${esc(o.name)}</b><div class="small muted">提交 ${o.submitted}</div></td><td><span class="pill">${({queued:'待成交',filled:o.side==='buy'?(o.confirm>r.date?'待确认':'已确认'):(r.receivables.some(c=>c.orderId===o.id)?'待到账':'已到账'),cancelled:'已撤销',rejected:'净值缺失，已撤回'})[o.status]}</span></td><td>${o.side==='buy'?'¥'+money(o.amount):o.units.toFixed(4)+'份'+(o.status==='filled'?'<div class="small muted">赎回净额 ¥'+money(o.amount)+'</div>':'')}${o.fee!==undefined?`<div class="small muted">费用 ¥${money(o.fee)}</div>`:''}</td><td>${o.price?`净值 ${o.price.toFixed(4)}<div class="small muted">${o.filled} 成交 · ${o.side==='buy'?o.confirm+' 确认':(o.settledAt||o.settle||'日期待核实')+' 到账'}</div>`:`<span class="small muted">${o.execute} 计划成交<br>成交净值尚不可见</span>`}</td><td>${o.status==='queued'&&!r.completed?`<button data-cancel="${o.id}">撤销</button>`:'—'}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">还没有订单。下一天不会自动帮你买入基金。</div>';
  document.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>act({type:'cancel',orderId:b.dataset.cancel}));
 }else renderReview();
}
function renderFunds(){const rows=view.funds.filter(f=>(!onlyMatch||f.match)&&(!search||(f.name+f.code).toLowerCase().includes(search.toLowerCase()))&&(!kind||f.type.includes(kind))).sort((a,b)=>sort==='amp'?(a.amp??Infinity)-(b.amp??Infinity):(b.change??-Infinity)-(a.change??-Infinity));$('fundCount').textContent=`${rows.length} 只候选 / 历史池 ${view.funds.length} 只 · 指标截止 ${view.market.asof} · 支付宝当时可买状态未复原`;
 $('fundList').innerHTML=rows.slice(0,pageSize).map(f=>`<article class="fund"><div class="fund-meta">${f.code} · ${esc(f.type)}</div><h3>${esc(f.name)}</h3>${compositionPreview(f)}<div class="fund-metrics"><div><span>首尾涨跌幅</span><b>${f.change===null?'—':pct(f.change)}</b></div><div><span>区间振幅</span><b>${f.amp===null?'—':(f.amp*100).toFixed(2)+'%'}</b></div></div><div class="tags"><span class="pill ${f.rule1?'lime':''}">横盘 ${f.rule1?'符合':'未满足'}</span><span class="pill ${f.rule2?'blue':''}">${phases[f.signal.phase]}</span></div>${curve(f.chart,'#397866',100)}<details><summary>查看筛选依据</summary><p>已披露净值 ${f.nav?.toFixed(4)||'—'} · ${f.navDate||'暂无'}。${f.signal.rangeStart?`原区间 ${f.signal.rangeStart}—${f.signal.rangeEnd}；首破 ${f.signal.firstBreakDate}${f.signal.confirmDate?'；确认 '+f.signal.confirmDate:''}${f.signal.exitDate?'；退出 '+f.signal.exitDate:''}。`:''}持仓按当时已披露的报告展示，点击“查看构成”了解明细。</p></details><div class="fund-foot"><span class="small muted">真实历史净值</span><button class="dark-btn" data-buy="${f.code}" ${view.run.completed||!f.nav?'disabled':''}>买入</button></div></article>`).join('')||'<div class="empty">没有匹配的基金。可以修改筛选策略，或查看全部历史基金。</div>';
 $('loadMore').hidden=rows.length<=pageSize;document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>trade(b.dataset.buy,'buy'));
}
function trade(code,side){const f=view.funds.find(f=>f.code===code),h=view.portfolio.holdings.find(h=>h.code===code),buy=side==='buy';showModal(`<div class="trade-layout"><section><div class="eyebrow">${buy?'BUY':'SELL'} / 虚拟订单</div><h2>${buy?'买入':'卖出'} ${esc(f.name)}</h2><div class="trade-price">已披露参考净值 · ${f.navDate}<b>${f.nav.toFixed(4)}</b>这不是成交价格。订单按成交日尚未揭晓的净值处理。</div><form id="tradeForm" class="trade-form"><label>${buy?'买入金额（含申购费，元）':'卖出份额'}<input id="tradeValue" type="number" step="any" min="${buy?'100':'0.0001'}" max="${buy?view.portfolio.cash:h.available}" value="${buy?Math.min(10000,Math.floor(view.portfolio.cash*100)/100):h.available}" required></label><div class="quick-amounts">${[.25,.5,1].map(n=>`<button type="button" data-fraction="${n}">${n*100}%${buy?'现金':'可卖'}</button>`).join('')}</div><p class="small muted">${buy?'可用现金 ¥'+money(view.portfolio.cash):'可卖份额 '+h.available.toFixed(4)}</p><label>这次决定的理由<textarea id="tradeReason" maxlength="1000" placeholder="例如：规则一与规则二同时满足，先用一小部分仓位观察。" required></textarea></label><div class="trade-summary">${buy?'申购费0.15%；T+1交易日确认份额。':'先进先出；不足7自然日赎回费1.5%，否则0.5%；T+2交易日到账。'}<br>以上为统一教学假设，不是该产品的真实历史费率。</div><p id="tradeError" class="error" role="alert"></p><button class="primary wide" type="submit">提交${buy?'买入':'卖出'}订单</button></form></section><aside class="trade-events" aria-label="交易时可见的市场事件">${eventCards(view.market)}</aside></div>`,true);
 document.querySelectorAll('[data-fraction]').forEach(b=>b.onclick=()=>{$('tradeValue').value=buy?Math.floor(view.portfolio.cash*Number(b.dataset.fraction)*100)/100:h.available*Number(b.dataset.fraction)});
 $('tradeForm').onsubmit=async e=>{e.preventDefault();const value=Number($('tradeValue').value),reason=$('tradeReason').value;if(!reason.trim()){$('tradeError').textContent='请写下这次决定的理由。';return}const ok=await act({type:side,code,[buy?'amount':'units']:value,reason});if(ok){modal.close();toast('订单已提交，尚未成交。可在交易订单中撤销。')}};
}
function renderReview(){
 const r=view.run,p=view.portfolio,revealed=reportReveals.get(r.id)||1,draft=$('reviewNote')?.value||'';
 $('workspace').innerHTML=reportMarkup(view,revealed)+`<section class="review-notebook"><div class="section-title"><div><h2>给未来的自己，留一条线索。</h2><p>主动笔记会成为报告里的证据。</p></div></div><form class="note-form" id="noteForm"><label>今天的复盘<textarea id="reviewNote" maxlength="1000" placeholder="我当时预期什么？实际发生什么？下一次只改变哪一个条件？" required></textarea></label><button class="dark-btn" type="submit">保存复盘</button></form><details class="raw-journal"><summary>查看完整交易与决策日志 · ${r.journal.length}条</summary><div class="journal">${[...r.journal].reverse().map(j=>`<article class="journal-entry"><time>${j.date}</time> <span class="pill">${({rules:'筛选策略',order:'交易决定',fill:'成交',cancel:'撤单',settle:'到账',dividend:'分红',note:'手动复盘',day:'推进一天',rejected:'订单撤回'})[j.type]||j.type}</span><p>${esc(j.text)}</p>${j.reason?`<p class="muted">当时的理由：${esc(j.reason)}</p>`:''}${j.price?`<p class="small muted">成交净值 ${j.price.toFixed(4)} · ${j.units.toFixed(4)}份 · 费用 ¥${money(j.fee)}</p>`:''}${j.amount?`<p class="small muted">¥${money(j.amount)}</p>`:''}${j.rules?`<details><summary>当时使用的筛选策略</summary><p>${j.rules.enabled.map(id=>id==='rule1'?'规则一 · 横盘':'规则二 · 突破').join(' ＋ ')}；${j.rules.days}自然日；振幅≤${j.rules.amp}%；涨跌${j.rules.min??'不限'}% 至 ${j.rules.max??'不限'}%；突破阶段 ${esc(j.rules.stage)}</p></details>`:''}</article>`).join('')||'<div class="empty">还没有记录。可以先写下这次练习的计划。</div>'}</div></details></section>`;
 $('reviewNote').value=draft;
 function reveal(n,scroll=true){reportReveals.set(r.id,Math.min(6,Math.max(revealed,n)));renderReview();if(scroll)$('reportChapter'+n)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'})}
 $('expandReport').onclick=()=>reveal(6,false);
 $('nextReportChapter')?.addEventListener('click',()=>reveal(revealed+1));
 document.querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>reveal(+b.dataset.chapter));
 $('reportDay').oninput=e=>{const template=document.createElement('template');template.innerHTML=reportChart(view,+e.target.value);for(const selector of ['.return-plot','.day-readout'])$('reportChart').querySelector(selector).innerHTML=template.content.querySelector(selector).innerHTML};
 $('printReport').onclick=()=>window.print();
 document.querySelectorAll('[data-report-mission]').forEach(b=>b.onclick=async()=>{const mission=view.report.missions[+b.dataset.reportMission],reason='下一局练习：'+mission.title+'。'+mission.body;if(r.journal.some(j=>j.type==='note'&&j.text===reason)){toast('这条练习已经保存在复盘里');return}if(await act({type:'note',reason}))toast('已加入复盘笔记')});
 $('noteForm').onsubmit=async e=>{e.preventDefault();const reason=$('reviewNote').value;if(await act({type:'note',reason})){if($('reviewNote'))$('reviewNote').value='';toast('复盘已保存')}};
 $('exportRun').onclick=()=>{const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),run:r,portfolio:p,report:view.report,assumptions:meta.assumptions,limitations:meta.limitations},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='时序_演练复盘_'+r.start+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
}
async function resume(id){try{view=await api('state?id='+encodeURIComponent(id));history.replaceState(null,'','/simulation.html?run='+id);tab=view.run.completed?'review':'funds';modal.close();renderRun()}catch(e){toast(e.message,true)}}
function bindResume(){document.querySelectorAll('[data-resume]').forEach(b=>b.onclick=()=>resume(b.dataset.resume))}
$('sessionsBtn').onclick=async()=>{try{meta=await api('bootstrap');showModal(`<div class="eyebrow">YOUR REHEARSALS</div><h2>我的演练</h2><p class="data-note">当前浏览器身份的服务端存档。收益按各次演练截止时点计算，已含实际发生的教学费用。清除Cookie或换设备后无法恢复，请及时导出。</p><div class="sessions">${meta.runs.map(r=>`<button class="session-card result-session" data-resume="${r.id}"><span class="session-title"><b>${r.start} 开始</b><small>${r.completed?'已结束':'进行中 · 第'+(r.elapsed+1)+'天'} · 初始 ¥${money(r.initial)}</small><small>目标 ${pct(r.target)} · 估值截至 ${r.date}</small></span><span class="session-performance"><small>${r.completed?'最终收益率':'当前收益率'}</small><strong class="${r.return>0?'positive':r.return<0?'negative':'neutral'}">${Number.isFinite(r.return)?pct(r.return):'—'}</strong><small>${Number.isFinite(r.profit)?(r.profit>=0?'+':'−')+'¥'+money(Math.abs(r.profit)):'盈亏暂不可用'}</small></span><span class="session-cta">${r.completed?'翻开我的报告':'继续演练'}</span></button>`).join('')||'<p class="muted">还没有演练存档。</p>'}</div>`,true);bindResume()}catch(e){toast(e.message,true)}};
async function boot(){try{meta=await api('bootstrap');const run=new URLSearchParams(location.search).get('run');if(run)await resume(run);else await loadPreview()}catch(e){$('app').innerHTML=`<section class="panel"><h2>暂时无法打开演练</h2><p class="error">${esc(e.message)}</p><button id="retry" style="margin-top:20px">重新载入</button> <a href="/">返回基金筛选</a></section>`;$('retry').onclick=boot}}
boot();

document.addEventListener('click',e=>{const b=e.target.closest('[data-composition]');if(b)showComposition(b.dataset.composition)});
